//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.645, BuildCommit: 6e9f98c9dbaacd42e09240f9386168f3b8317f96)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14, SDK: 16, Tool: ld (1215)
//    - LC_SOURCE_VERSION: 1031.0.0.0.0
//
#ifndef ROCKImpersonateable_Protocol_h
#define ROCKImpersonateable_Protocol_h
@import Foundation;

#include "ROCKImpersonatable-Protocol.h"

@protocol ROCKImpersonateable <ROCKImpersonatable>

@required

@optional

@end

#endif /* ROCKImpersonateable_Protocol_h */
