//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.645, BuildCommit: 6e9f98c9dbaacd42e09240f9386168f3b8317f96)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14, SDK: 16, Tool: ld (1215)
//    - LC_SOURCE_VERSION: 1031.0.0.0.0
//
#ifndef SimDiskImage_h
#define SimDiskImage_h
@import Foundation;

#include "SimDiskImageIdentifier.h"
#include "SimDiskImageRuntimeInfo.h"

@class NSDate, NSDictionary, NSError, NSNumber, NSObject, NSString, NSURL;

@interface SimDiskImage : NSObject

@property (retain, nonatomic) SimDiskImageIdentifier *identifier;
@property (retain, nonatomic) NSURL *imageURL;
@property (copy, nonatomic) NSString *userInterfaceDescription;
@property (nonatomic) unsigned long long imageState;
@property (nonatomic) unsigned long long unusableSubstate;
@property (retain, nonatomic) NSError *unusableError;
@property (nonatomic) _Bool deletable;
@property (retain, nonatomic) NSURL *mountURL;
@property (copy, nonatomic) NSNumber *sizeBytes;
@property (nonatomic) unsigned long long imageKind;
@property (nonatomic) long long mountingMode;
@property (retain, nonatomic) SimDiskImageRuntimeInfo *runtimeInfo;
@property (retain, nonatomic) NSDictionary *userInfo;
@property (nonatomic) unsigned long long signatureState;
@property (nonatomic) unsigned long long imageFormat;
@property (nonatomic) unsigned long long imageWritePolicy;
@property (nonatomic) unsigned long long imageMountPolicy;
@property (nonatomic) _Bool expandable;
@property (retain, nonatomic) NSDate *lastUsedAt;
@property (copy, nonatomic) NSString *sourceParentIdentifier;
@property (retain, nonatomic) NSURL *sourceParentBundleImageURL;
@property (retain, nonatomic) NSURL *sourceParentBundleMountURL;
@property (copy, nonatomic) NSString *cryptexVariant;
@property (readonly, nonatomic) NSString *name;
@property (readonly, nonatomic) NSString *unusableErrorMessage;
@property (readonly, nonatomic) NSString *unusableErrorDetail;

/* instance methods */
- (id)initWithIdentifier:(id)identifier imageURL:(id)url imageState:(unsigned long long)state unusableSubstate:(unsigned long long)substate unusableError:(id)error deletable:(_Bool)deletable expandable:(_Bool)expandable mountURL:(id)url sizeBytes:(id)bytes imageKind:(unsigned long long)kind mountingMode:(long long)mode runtimeInfo:(id)info signatureState:(unsigned long long)state imageFormat:(unsigned long long)format imageWritePolicy:(unsigned long long)policy imageMountPolicy:(unsigned long long)policy sourceParentIdentifier:(id)identifier sourceParentBundleImageURL:(id)url sourceParentBundleMountURL:(id)url cryptexVariant:(id)variant lastUsedAt:(id)at userInfo:(id)info;
- (id)initFromXPCDictionary:(id)xpcdictionary error:(id *)error;
- (id)description;

@end

#endif /* SimDiskImage_h */
