//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.645, BuildCommit: 6e9f98c9dbaacd42e09240f9386168f3b8317f96)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14, SDK: 16, Tool: ld (1215)
//    - LC_SOURCE_VERSION: 1031.0.0.0.0
//
#ifndef SimDeviceType_h
#define SimDeviceType_h
@import Foundation;
@import CoreGraphics;

#include "SimDeviceIODeviceTypeInterface-Protocol.h"
#include "SimProfileBundle.h"

@class NSArray, NSDictionary, NSObject, NSString, NSURL;
@protocol OS_dispatch_queue;

@interface SimDeviceType : NSObject <SimDeviceIODeviceTypeInterface>

@property (retain, nonatomic) SimProfileBundle * _Nullable bundle;
@property (nonatomic) NSString * _Nullable name;
@property (nonatomic) NSString * _Nullable identifier;
@property (copy, nonatomic) NSString * _Nullable modelIdentifier;
@property (nonatomic) CGSize mainScreenSize;
@property (nonatomic) CGSize mainScreenDPI;
@property (nonatomic) CGSize defaultCanvasSize;
@property (nonatomic) float mainScreenScale;
@property (nonatomic) unsigned int mainScreenColorspace;
@property (nonatomic) NSURL * _Nullable framebufferMaskURL;
@property (copy, nonatomic) NSURL * _Nullable sensorBarImageURL;
@property (copy, nonatomic) NSArray * _Nullable supportedArchs;
@property (copy, nonatomic) NSArray * _Nullable supportedArchStrings;
@property (nonatomic) unsigned int minRuntimeVersion;
@property (nonatomic) unsigned int maxRuntimeVersion;
@property (nonatomic) unsigned int minCoreSimulatorFrameworkVersion;
@property (nonatomic) unsigned int maxCoreSimulatorFrameworkVersion;
@property (nonatomic) unsigned int createByDefaultForRuntimeVersionMin;
@property (nonatomic) unsigned int createByDefaultForRuntimeVersionMax;
@property (nonatomic) unsigned int pairByDefaultForRuntimeVersionMin;
@property (nonatomic) unsigned int pairByDefaultForRuntimeVersionMax;
@property (copy, nonatomic) NSString * _Nullable springBoardConfigName;
@property (copy, nonatomic) NSString * _Nullable productClass;
@property (copy, nonatomic) NSArray * _Nullable supportedProductFamilyIDs;
@property (copy, nonatomic) NSDictionary * _Nullable environment_extra;
@property (nonatomic) NSDictionary * _Nullable capabilities;
@property (copy, nonatomic) NSArray * _Nullable aliases;
@property (copy, nonatomic) NSDictionary * _Nullable supportedFeatures;
@property (copy, nonatomic) NSDictionary * _Nullable supportedFeaturesConditionalOnRuntime;
@property (retain, nonatomic) NSString * _Nullable chromeIdentifier;
@property (retain, nonatomic) NSString * _Nullable userInterfaceIdentifier;
@property (copy, nonatomic) NSDictionary * _Nullable requiredRuntimeFeatures;
@property (readonly, nonatomic) int productFamilyID;
@property (readonly, nonatomic) NSString * _Nullable productFamily;
@property (readonly, nonatomic) NSURL * _Nullable bundleURL;
@property (readonly, nonatomic) NSObject<OS_dispatch_queue> * _Nullable memoizableSerializerQueue;
@property (readonly) NSUInteger hash;
@property (readonly) _Nullable Class superclass;
@property (readonly, copy) NSString * _Nullable description;
@property (readonly, copy) NSString * _Nullable debugDescription;

/* instance methods */
- (_Nullable id)initWithBundle:(_Nullable id)bundle error:(id _Nullable * _Nullable)error;
- (_Nullable id)bundlePath;
- (_Nullable id)environment;
- (_Bool)supportsFeature:(_Nullable id)feature;
- (_Bool)supportsFeatureConditionally:(_Nullable id)conditionally;
- (long long)compare:(_Nullable id)compare;
- (_Nullable Class)deviceClass;

@end

#endif /* SimDeviceType_h */
