//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.645, BuildCommit: 6e9f98c9dbaacd42e09240f9386168f3b8317f96)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14, SDK: 16, Tool: ld (1215)
//    - LC_SOURCE_VERSION: 1031.0.0.0.0
//
#ifndef SimDeviceIORuntimeInterface_Protocol_h
#define SimDeviceIORuntimeInterface_Protocol_h
@import Foundation;

#include "ROCKMemoizable-Protocol.h"

@class NSDictionary, NSString, NSURL;

@protocol SimDeviceIORuntimeInterface <ROCKMemoizable>

@required

@property (readonly, nonatomic) NSString *name;
@property (readonly, nonatomic) NSString *identifier;
@property (readonly, nonatomic) unsigned int version;
@property (readonly, nonatomic) NSString *platformIdentifier;
@property (readonly, nonatomic) unsigned int equivalentIOSVersion;
@property (readonly, nonatomic) NSURL *runtimeRootURL;
@property (readonly, nonatomic) NSURL *bundleURL;
@property (readonly, nonatomic) NSURL *platformResourcesURL;
@property (readonly, nonatomic) NSDictionary *requiredHostServices;

/* required instance methods */
- (_Bool)supportsFeature:(id)feature;
- (_Bool)supportsFeatureConditionally:(id)conditionally;

@optional

@end

#endif /* SimDeviceIORuntimeInterface_Protocol_h */
