//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.645, BuildCommit: 6e9f98c9dbaacd42e09240f9386168f3b8317f96)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14, SDK: 16, Tool: ld (1215)
//    - LC_SOURCE_VERSION: 1031.0.0.0.0
//
#ifndef SimDiskImageIdentifier_h
#define SimDiskImageIdentifier_h
@import Foundation;

#include "NSCopying-Protocol.h"

@class NSObject, NSString;

@interface SimDiskImageIdentifier : NSObject <NSCopying>

@property (copy, nonatomic) NSString *opaqueValue;

/* instance methods */
- (id)initWithOpaqueValue:(id)value;
- (id)copyWithZone:(struct _NSZone *)zone;
- (_Bool)isEqual:(id)equal;
- (unsigned long long)hash;
- (id)description;

@end

#endif /* SimDiskImageIdentifier_h */
