//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.645, BuildCommit: 6e9f98c9dbaacd42e09240f9386168f3b8317f96)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14, SDK: 16, Tool: ld (1215)
//    - LC_SOURCE_VERSION: 1031.0.0.0.0
//
#ifndef SimDeviceIOInterface_Protocol_h
#define SimDeviceIOInterface_Protocol_h
@import Foundation;

#include "ROCKImpersonateable-Protocol.h"
#include "SimDeviceIODeviceTypeInterface-Protocol.h"
#include "SimDeviceIORuntimeInterface-Protocol.h"

@class NSArray, NSString, NSURL, NSUUID;

@protocol SimDeviceIOInterface <ROCKImpersonateable>

@required

@property (readonly, nonatomic) NSUUID *deviceUDID;
@property (readonly, nonatomic) NSString *deviceName;
@property (readonly, nonatomic) id <SimDeviceIORuntimeInterface> deviceRuntime;
@property (readonly, nonatomic) id <SimDeviceIODeviceTypeInterface> deviceType;
@property (readonly, nonatomic) NSURL *deviceDataURL;
@property (readonly, nonatomic) NSURL *deviceLogURL;
@property (readonly, nonatomic) NSArray *ioPorts;

/* required instance methods */
- (_Bool)registerPort:(unsigned int)port service:(id)service error:(id *)error;
- (_Bool)unregisterService:(id)service error:(id *)error;
- (_Bool)postDarwinNotification:(id)notification error:(id *)error;
- (_Bool)getDarwinNotificationState:(unsigned long long *)state name:(id)name error:(id *)error;
- (_Bool)setDarwinNotificationState:(unsigned long long)state name:(id)name error:(id *)error;
- (_Bool)postHostNotification:(id)notification portUUID:(id)uuid portClass:(unsigned short)_class info:(id)info error:(id *)error;
- (_Bool)supportsFeature:(id)feature;
- (_Bool)isOSFeatureEnabled:(id)enabled domain:(id)domain;
- (void)connectIOPort:(id)ioport completionQueue:(id)queue completionHandler:(id /* block */)handler;
- (void)disconnectIOPort:(id)ioport completionQueue:(id)queue completionHandler:(id /* block */)handler;

@optional

@end

#endif /* SimDeviceIOInterface_Protocol_h */
