//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.645, BuildCommit: 6e9f98c9dbaacd42e09240f9386168f3b8317f96)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14, SDK: 16, Tool: ld (1215)
//    - LC_SOURCE_VERSION: 1031.0.0.0.0
//
#ifndef SimDeviceIOServerLogger_h
#define SimDeviceIOServerLogger_h
@import Foundation;

#include "SimDeviceIOLogger-Protocol.h"

@class NSObject, NSString;

@interface SimDeviceIOServerLogger : NSObject <SimDeviceIOLogger>

@property (copy, nonatomic) NSString *bundleIdentifier;
@property (readonly) NSUInteger hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initForBundleIdentifier:(id)identifier;
- (void)deviceIOLogLevel:(int)level message:(id)message;
- (void)deviceIOLogError:(id)error message:(id)message;

@end

#endif /* SimDeviceIOServerLogger_h */
