//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.645, BuildCommit: 6e9f98c9dbaacd42e09240f9386168f3b8317f96)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14, SDK: 16, Tool: ld (1215)
//    - LC_SOURCE_VERSION: 1031.0.0.0.0
//
#ifndef SimDeviceIOClient_h
#define SimDeviceIOClient_h
@import Foundation;

#include "SimDeviceIO.h"
#include "SimDeviceIOClientProtocol-Protocol.h"

@class NSArray, NSObject, NSString;
@protocol OS_dispatch_queue;

@interface SimDeviceIOClient : SimDeviceIO <SimDeviceIOClientProtocol>

@property (retain, nonatomic) NSArray *deviceIOPorts;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> *executionQueue;
@property (nonatomic) unsigned long long bootGeneration;
@property (readonly, nonatomic) NSArray *ioPorts;
@property (readonly) NSUInteger hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithDevice:(id)device errorQueue:(id)queue errorHandler:(id /* block */)handler;
- (void)updateIOPorts;
- (_Bool)_handleXPCNotification:(id)xpcnotification;

@end

#endif /* SimDeviceIOClient_h */
