//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.645, BuildCommit: 6e9f98c9dbaacd42e09240f9386168f3b8317f96)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14, SDK: 16, Tool: ld (1215)
//    - LC_SOURCE_VERSION: 1031.0.0.0.0
//
#ifndef SimDisplayDefaultDescriptorState_h
#define SimDisplayDefaultDescriptorState_h
@import Foundation;

#include "SimDisplayDescriptorState-Protocol.h"

@class NSObject, NSString, NSURL;
@protocol OS_dispatch_queue;

@interface SimDisplayDefaultDescriptorState : NSObject <SimDisplayDescriptorState>

@property (nonatomic) int powerState;
@property (nonatomic) unsigned short displayClass;
@property (nonatomic) unsigned int defaultWidthForDisplay;
@property (nonatomic) unsigned int defaultHeightForDisplay;
@property (nonatomic) unsigned int defaultPixelFormat;
@property (retain, nonatomic) NSURL *mask;
@property (readonly, nonatomic) NSObject<OS_dispatch_queue> *memoizableSerializerQueue;
@property (readonly) NSUInteger hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, nonatomic) NSString *portIdentifier;

/* class methods */
+ (id)defaultDisplayDescriptorStateWithPowerState:(int)state displayClass:(unsigned short)_class width:(unsigned int)width height:(unsigned int)height pixelFormat:(unsigned int)format mask:(id)mask;

/* instance methods */

@end

#endif /* SimDisplayDefaultDescriptorState_h */
