//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.645, BuildCommit: 6e9f98c9dbaacd42e09240f9386168f3b8317f96)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14, SDK: 16, Tool: ld (1215)
//    - LC_SOURCE_VERSION: 1031.0.0.0.0
//
#ifndef SimDeviceIOLoadedBundle_h
#define SimDeviceIOLoadedBundle_h
@import Foundation;

@class NSBundle, NSObject;
@protocol SimDeviceIOBundleInterface;

@interface SimDeviceIOLoadedBundle : NSObject

@property (retain, nonatomic) NSBundle *bundle;
@property (retain, nonatomic) id <SimDeviceIOBundleInterface> bundleInterface;

/* class methods */
+ (id)loadedBundleForURL:(id)url;

/* instance methods */
- (id)initWithURL:(id)url;

@end

#endif /* SimDeviceIOLoadedBundle_h */
