//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.645, BuildCommit: 6e9f98c9dbaacd42e09240f9386168f3b8317f96)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14, SDK: 16, Tool: ld (1215)
//    - LC_SOURCE_VERSION: 1031.0.0.0.0
//
#ifndef SimDeviceIO_h
#define SimDeviceIO_h
@import Foundation;

#include "SimDevice.h"
#include "SimDeviceIODeviceTypeInterface-Protocol.h"
#include "SimDeviceIOInterface-Protocol.h"
#include "SimDeviceIOProtocol-Protocol.h"
#include "SimDeviceIORuntimeInterface-Protocol.h"

@class NSArray, NSObject, NSString, NSURL, NSUUID;
@protocol OS_dispatch_queue;

@interface SimDeviceIO : NSObject <SimDeviceIOInterface, SimDeviceIOProtocol>

@property (weak, nonatomic) SimDevice *device;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> *errorQueue;
@property (copy, nonatomic) id /* block */ errorHandler;
@property (readonly, nonatomic) NSUUID *deviceUDID;
@property (readonly, nonatomic) NSString *deviceName;
@property (readonly, nonatomic) id <SimDeviceIORuntimeInterface> deviceRuntime;
@property (readonly, nonatomic) id <SimDeviceIODeviceTypeInterface> deviceType;
@property (readonly, nonatomic) NSURL *deviceDataURL;
@property (readonly, nonatomic) NSURL *deviceLogURL;
@property (readonly, nonatomic) NSArray *ioPorts;
@property (readonly) NSUInteger hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)ioForSimDevice:(id)device errorQueue:(id)queue errorHandler:(id /* block */)handler;

/* instance methods */
- (id)initWithDevice:(id)device errorQueue:(id)queue errorHandler:(id /* block */)handler;
- (id)ioPortForUUID:(id)uuid;
- (_Bool)registerPort:(unsigned int)port service:(id)service error:(id *)error;
- (_Bool)unregisterService:(id)service error:(id *)error;
- (_Bool)postDarwinNotification:(id)notification error:(id *)error;
- (_Bool)getDarwinNotificationState:(unsigned long long *)state name:(id)name error:(id *)error;
- (_Bool)setDarwinNotificationState:(unsigned long long)state name:(id)name error:(id *)error;
- (_Bool)postHostNotification:(id)notification portUUID:(id)uuid portClass:(unsigned short)_class info:(id)info error:(id *)error;
- (_Bool)supportsFeature:(id)feature;
- (_Bool)isOSFeatureEnabled:(id)enabled domain:(id)domain;
- (void)connectIOPort:(id)ioport completionQueue:(id)queue completionHandler:(id /* block */)handler;
- (void)disconnectIOPort:(id)ioport completionQueue:(id)queue completionHandler:(id /* block */)handler;

@end

#endif /* SimDeviceIO_h */
