//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.645, BuildCommit: 6e9f98c9dbaacd42e09240f9386168f3b8317f96)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14, SDK: 16, Tool: ld (1215)
//    - LC_SOURCE_VERSION: 1031.0.0.0.0
//
#ifndef SimDeviceIOServer_h
#define SimDeviceIOServer_h
@import Foundation;
#include <os/lock.h>

#include "SimDeviceIO.h"
#include "SimDeviceIODeviceTypeInterface-Protocol.h"
#include "SimDeviceIOInterface-Protocol.h"
#include "SimDeviceIORuntimeInterface-Protocol.h"

@class NSArray, NSDictionary, NSError, NSString, NSURL, NSUUID;

@interface SimDeviceIOServer : SimDeviceIO <SimDeviceIOInterface> {
    /* instance variables */
    os_unfair_lock _lock;
    _Atomic long long _loadGeneration;
}

@property (retain, nonatomic) NSArray *ioPorts;
@property (retain, nonatomic) NSArray *connectedPorts;
@property (retain, nonatomic) NSArray *connectedBundles;
@property (retain, nonatomic) NSDictionary *loadedBundles;
@property (retain, nonatomic) NSDictionary *loadedBundlesByPortUUID;
@property (retain, nonatomic) NSError *bundleLoadError;
@property (nonatomic) _Bool hasPreparedForShutdown;
@property (nonatomic) _Bool hasNotifiedDidShutdown;
@property (readonly, nonatomic) NSUUID *deviceUDID;
@property (readonly, nonatomic) NSString *deviceName;
@property (readonly, nonatomic) id <SimDeviceIORuntimeInterface> deviceRuntime;
@property (readonly, nonatomic) id <SimDeviceIODeviceTypeInterface> deviceType;
@property (readonly, nonatomic) NSURL *deviceDataURL;
@property (readonly, nonatomic) NSURL *deviceLogURL;
@property (readonly) NSUInteger hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)discoverBundleDependencies:(id)dependencies;

/* instance methods */
- (_Bool)loadAllBundlesWithError:(id *)error;
- (void)_criticalError:(id)error inLoadGeneration:(long long)generation fromBundle:(id)bundle recoveryStrategy:(unsigned long long)strategy;
- (_Bool)prepareForBootWithOptions:(id)options error:(id *)error;
- (void)notifyDeviceDidBoot;
- (void)prepareForShutdown;
- (void)notifyDeviceDidShutdown;
- (void)unloadAllBundles;
- (id)legacyHIDDescriptorState;
- (id)internalDisplayDescriptorState;
- (id)externalDisplayDescriptorState;
- (id)audioHostRouteDescriptorState;
- (void)connectIOPort:(id)ioport completionQueue:(id)queue completionHandler:(id /* block */)handler;
- (void)disconnectIOPort:(id)ioport completionQueue:(id)queue completionHandler:(id /* block */)handler;
- (_Bool)registerPort:(unsigned int)port service:(id)service error:(id *)error;
- (_Bool)unregisterService:(id)service error:(id *)error;
- (_Bool)postDarwinNotification:(id)notification error:(id *)error;
- (_Bool)getDarwinNotificationState:(unsigned long long *)state name:(id)name error:(id *)error;
- (_Bool)setDarwinNotificationState:(unsigned long long)state name:(id)name error:(id *)error;
- (_Bool)postHostNotification:(id)notification portUUID:(id)uuid portClass:(unsigned short)_class info:(id)info error:(id *)error;
- (_Bool)isOSFeatureEnabled:(id)enabled domain:(id)domain;

@end

#endif /* SimDeviceIOServer_h */
