//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.645, BuildCommit: 6e9f98c9dbaacd42e09240f9386168f3b8317f96)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14, SDK: 16, Tool: ld (1215)
//    - LC_SOURCE_VERSION: 1031.0.0.0.0
//
#ifndef SimIdentitySystem_Protocol_h
#define SimIdentitySystem_Protocol_h
@import Foundation;

#include "NSObject-Protocol.h"

@class NSObject;
@protocol OS_dispatch_queue;

@protocol SimIdentitySystem <NSObject>

@required

@property (readonly, nonatomic) NSObject<OS_dispatch_queue> *stateProtectionQueue;

/* required instance methods */
- (void)enqueueRequestOperation:(id /* block */)operation forIdentityDevice:(id)device;
- (void)cancelQueuedOperationForIdentityDevice:(id)device;

@optional

@end

#endif /* SimIdentitySystem_Protocol_h */
