//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.645, BuildCommit: 6e9f98c9dbaacd42e09240f9386168f3b8317f96)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14, SDK: 16, Tool: ld (1215)
//    - LC_SOURCE_VERSION: 1031.0.0.0.0
//
#ifndef SimIdentityManager_h
#define SimIdentityManager_h
@import Foundation;

#include "SimIdentitySystem-Protocol.h"

@class NSArray, NSMutableDictionary, NSObject, NSString;
@protocol OS_dispatch_queue;

@interface SimIdentityManager : NSObject <SimIdentitySystem>

@property (retain, nonatomic) NSObject<OS_dispatch_queue> *queue;
@property (retain, nonatomic) NSMutableDictionary *devices;
@property (retain, nonatomic) NSArray *pendingRequests;
@property (nonatomic) _Bool hasPendingRequestCompletion;
@property (readonly, nonatomic) NSObject<OS_dispatch_queue> *stateProtectionQueue;
@property (readonly) NSUInteger hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)sharedManager;

/* instance methods */
- (id)init;
- (void)deviceSetCreated:(id)created;
- (void)_onQueue_checkDeviceSetForNewDevices:(id)devices;
- (void)_onQueue_addDevice:(id)device;
- (void)_onQueue_removeDevice:(id)device;
- (void)_onQueue_deviceDidShutdown:(id)shutdown;
- (void)_onQueue_peerHandler:(id)handler peer:(id)peer;
- (void)enqueueRequestOperation:(id /* block */)operation forIdentityDevice:(id)device;
- (void)cancelQueuedOperationForIdentityDevice:(id)device;
- (void)_onQueue_processNextQueuedRequest;

@end

#endif /* SimIdentityManager_h */
