//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.645, BuildCommit: 6e9f98c9dbaacd42e09240f9386168f3b8317f96)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14, SDK: 16, Tool: ld (1215)
//    - LC_SOURCE_VERSION: 1031.0.0.0.0
//
#ifndef SimKnownSDKEntry_h
#define SimKnownSDKEntry_h
@import Foundation;

#include "SimPlatformInfo.h"
#include "SimSDKInfo.h"

@class NSObject;

@interface SimKnownSDKEntry : NSObject

@property (retain, nonatomic) SimPlatformInfo *platform;
@property (retain, nonatomic) SimSDKInfo *sdk;

/* class methods */
+ (id)entryWithPlatform:(id)platform sdk:(id)sdk;

/* instance methods */

@end

#endif /* SimKnownSDKEntry_h */
