//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.645, BuildCommit: 6e9f98c9dbaacd42e09240f9386168f3b8317f96)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14, SDK: 16, Tool: ld (1215)
//    - LC_SOURCE_VERSION: 1031.0.0.0.0
//
#ifndef SimLocalThrowable_h
#define SimLocalThrowable_h
@import Foundation;

@class NSObject;

@interface SimLocalThrowable : NSObject

@property (retain, nonatomic) id data;

/* class methods */
+ (id)throwableWithData:(id)data;

/* instance methods */
- (id)initWithData:(id)data;

@end

#endif /* SimLocalThrowable_h */
