//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.645, BuildCommit: 6e9f98c9dbaacd42e09240f9386168f3b8317f96)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14, SDK: 16, Tool: ld (1215)
//    - LC_SOURCE_VERSION: 1031.0.0.0.0
//
#ifndef SimLegacyHIDDescriptorState_Protocol_h
#define SimLegacyHIDDescriptorState_Protocol_h
@import Foundation;

#include "ROCKMemoizable-Protocol.h"
#include "SimDeviceIOPortDescriptorState-Protocol.h"

@class NSString;

@protocol SimLegacyHIDDescriptorState <ROCKMemoizable, SimDeviceIOPortDescriptorState>

@required

@property (readonly, nonatomic) NSString *platformResourcesPath;

@optional

@end

#endif /* SimLegacyHIDDescriptorState_Protocol_h */
