//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.645, BuildCommit: 6e9f98c9dbaacd42e09240f9386168f3b8317f96)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14, SDK: 16, Tool: ld (1215)
//    - LC_SOURCE_VERSION: 1031.0.0.0.0
//
#ifndef SimNearbyDevice_h
#define SimNearbyDevice_h
@import Foundation;
@import CoreGraphics;

@class NSMutableArray, NSObject;
@protocol SimDeviceProtocol;

@interface SimNearbyDevice : NSObject

@property (retain, nonatomic) id <SimDeviceProtocol> device;
@property (nonatomic) CGRect deviceRect;
@property (nonatomic) double deviceRotation;
@property (nonatomic) _Bool hasPendingUpdate;
@property (retain, nonatomic) NSMutableArray *clients;

/* instance methods */
- (id)initWithDevice:(id)device;

@end

#endif /* SimNearbyDevice_h */
