//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.645, BuildCommit: 6e9f98c9dbaacd42e09240f9386168f3b8317f96)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14, SDK: 16, Tool: ld (1215)
//    - LC_SOURCE_VERSION: 1031.0.0.0.0
//
#ifndef SimNearbyDeviceManager_h
#define SimNearbyDeviceManager_h
@import Foundation;
@import CoreGraphics;

@class NSMutableDictionary, NSMutableSet, NSObject;
@protocol OS_dispatch_queue, OS_dispatch_source;

@interface SimNearbyDeviceManager : NSObject

@property (retain, nonatomic) NSObject<OS_dispatch_queue> *queue;
@property (retain, nonatomic) NSMutableSet *knownDevices;
@property (retain, nonatomic) NSMutableDictionary *bootedDevices;
@property (retain, nonatomic) NSObject<OS_dispatch_source> *updateTimer;
@property (nonatomic) _Bool isTimerScheduled;
@property (nonatomic) unsigned long long updateMode;

/* class methods */
+ (id)sharedManager;

/* instance methods */
- (id)init;
- (void)deviceSetCreated:(id)created;
- (void)_onQueue_checkDeviceSetForNewDevices:(id)devices;
- (void)_onQueue_addDevice:(id)device;
- (void)_onQueue_removeDevice:(id)device;
- (void)_onQueue_deviceDidBoot:(id)boot;
- (void)_onQueue_deviceDidShutdown:(id)shutdown;
- (void)_onQueue_peerDied:(id)died udid:(id)udid;
- (void)_onQueue_peerCheckedIn:(id)in discoveryToken:(id)token udid:(id)udid reply:(id)reply;
- (void)_onQueue_device:(id)queue_device connectedPeer:(id)peer;
- (_Bool)updateDevice:(id)device rect:(CGRect)rect rotation:(double)rotation error:(id *)error;
- (void)_onQueue_scheduleUpdateIfNeededInMode:(unsigned long long)mode;
- (void)_onQueue_notifyPeersDeviceBoot:(id)boot;
- (void)_onQueue_notifyPeersDeviceShutdown:(id)shutdown;
- (void)_onQueue_notifyPeersNewTokenFromDevice:(id)device token:(id)token;
- (void)_onQueue_notifyPeersCancelTokenFromDevice:(id)device token:(id)token;
- (void)_onQueue_notifyPeersBroadcastFrom:(id)from payload:(id)payload;
- (void)_onQueue_updateTimerFired;
- (void)_onQueue_broadcastMessage:(id)message excluding:(id)excluding;

@end

#endif /* SimNearbyDeviceManager_h */
