//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.645, BuildCommit: 6e9f98c9dbaacd42e09240f9386168f3b8317f96)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14, SDK: 16, Tool: ld (1215)
//    - LC_SOURCE_VERSION: 1031.0.0.0.0
//
#ifndef SimNotificationManagerToken_h
#define SimNotificationManagerToken_h
@import Foundation;

@class NSObject;

@interface SimNotificationManagerToken : NSObject

@property (copy, nonatomic) id /* block */ unregisterBlock;

/* class methods */
+ (id)tokenForManager:(id)manager registrationID:(unsigned long long)id;

/* instance methods */
- (id)initForManager:(id)manager registrationID:(unsigned long long)id;
- (void)dealloc;
- (void)invalidate;

@end

#endif /* SimNotificationManagerToken_h */
