//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.645, BuildCommit: 6e9f98c9dbaacd42e09240f9386168f3b8317f96)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14, SDK: 16, Tool: ld (1215)
//    - LC_SOURCE_VERSION: 1031.0.0.0.0
//
#ifndef SimProfileBundle_h
#define SimProfileBundle_h
@import Foundation;
#include <sys/time.h>

@class NSDictionary, NSObject, NSString, NSURL;

@interface SimProfileBundle : NSObject

@property (nonatomic) struct __CFBundle * cfBundle;
@property (retain, nonatomic) NSURL *bundleURL;
@property (retain, nonatomic) NSString *bundlePath;
@property (retain, nonatomic) NSString *bundleIdentifier;
@property (retain, nonatomic) NSDictionary *infoDictionary;
@property (retain, nonatomic) NSDictionary *localInfoDictionary;
@property (retain, nonatomic) Class principalClass;
@property (nonatomic) void * binaryHandle;
@property (retain, nonatomic) NSString *infoPlistPath;
@property (nonatomic) unsigned int packedVersion;
@property (nonatomic) struct timespec ctime;
@property (readonly, nonatomic) NSDictionary *fileToTimeMap;

/* class methods */
+ (id)extraCheckMap;
+ (id)bundleWithURL:(id)url error:(id *)error;
+ (id)bundleWithPath:(id)path error:(id *)error;
+ (id)bundleWithPath:(id)path loadBundle:(_Bool)bundle error:(id *)error;

/* instance methods */
- (id)initWithURL:(id)url error:(id *)error;
- (id)initWithURL:(id)url loadBundle:(_Bool)bundle error:(id *)error;
- (id)initWithPath:(id)path error:(id *)error;
- (id)initWithPath:(id)path loadBundle:(_Bool)bundle error:(id *)error;
- (void)dealloc;
- (_Bool)loadBundleWithError:(id *)error;
- (id)description;
- (id)pathForResource:(id)resource ofType:(id)type;
- (id)URLForResource:(id)resource withExtension:(id)extension;
- (id)objectForInfoDictionaryKey:(id)key;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)equal;
- (_Bool)isEqualToProfile:(id)profile;
- (unsigned long long)filesystemStatus;

@end

#endif /* SimProfileBundle_h */
