//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.645, BuildCommit: 6e9f98c9dbaacd42e09240f9386168f3b8317f96)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14, SDK: 16, Tool: ld (1215)
//    - LC_SOURCE_VERSION: 1031.0.0.0.0
//
#ifndef SimProfilesPathMonitor_h
#define SimProfilesPathMonitor_h
@import Foundation;

#include "SimNotificationManagerToken.h"

@class NSArray, NSMutableArray, NSMutableDictionary, NSObject, SimServiceContext;
@protocol OS_dispatch_queue;

@interface SimProfilesPathMonitor : NSObject

@property (retain, nonatomic) NSObject<OS_dispatch_queue> *monitorQueue;
@property (retain, nonatomic) NSMutableArray *leafMonitorSources;
@property (retain, nonatomic) NSMutableArray *parentMonitorSources;
@property (retain, nonatomic) NSMutableDictionary *monitoredPathsDict;
@property (weak, nonatomic) SimServiceContext *serviceContext;
@property (nonatomic) SimNotificationManagerToken *volumeManagerToken;
@property (readonly, nonatomic) NSArray *monitoredPaths;

/* class methods */
+ (id)profilesPathMonitorForContext:(id)context;

/* instance methods */
- (id)initWithContext:(id)context;
- (void)monitorDefaultProfilePaths;
- (void)monitorProfilesPath:(id)path;
- (void)fence;
- (void)_monitorProfilesPath:(id)path;
- (void)_monitorProfilesParentDirectory:(int)directory nextPathComponent:(id)component path:(id)path;
- (void)_monitorProfilesDirectory:(int)directory path:(id)path;
- (void)_monitorProfilesDirectory:(int)directory path:(id)path forSubDirectory:(id)directory updateBlock:(id /* block */)block;
- (void)_monitorProfilesSubDirectory:(int)directory path:(id)path updateBlock:(id /* block */)block;
- (void)_diskWillUnmount:(id)unmount;

@end

#endif /* SimProfilesPathMonitor_h */
