//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.645, BuildCommit: 6e9f98c9dbaacd42e09240f9386168f3b8317f96)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14, SDK: 16, Tool: ld (1215)
//    - LC_SOURCE_VERSION: 1031.0.0.0.0
//
#ifndef SimRuntimePairingRequirements_h
#define SimRuntimePairingRequirements_h
@import Foundation;

@class NSArray, NSObject;

@interface SimRuntimePairingRequirements : NSObject

@property (nonatomic) unsigned int minOSVersion;
@property (copy, nonatomic) NSArray *supportedProductFamilies;
@property (nonatomic) unsigned long long maxPairs;

/* instance methods */

@end

#endif /* SimRuntimePairingRequirements_h */
