//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.645, BuildCommit: 6e9f98c9dbaacd42e09240f9386168f3b8317f96)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14, SDK: 16, Tool: ld (1215)
//    - LC_SOURCE_VERSION: 1031.0.0.0.0
//
#ifndef SimRuntimeMapData_h
#define SimRuntimeMapData_h
@import Foundation;
#include <os/lock.h>

#include "SimServiceContext.h"

@class NSDictionary, NSMutableDictionary, NSObject, NSURL;

@interface SimRuntimeMapData : NSObject {
    /* instance variables */
    os_unfair_lock _lock;
    _Atomic _Bool _needsClearCache;
    NSMutableDictionary *_cachedRuntimeKeys;
}

@property (retain, nonatomic) NSURL *persistenceURL;
@property (retain, nonatomic) SimServiceContext *serviceContext;
@property (retain, nonatomic) NSDictionary *preferredRuntimeBuildBySDKBuild;
@property (retain, nonatomic) NSDictionary *userOverrides;

/* instance methods */
- (id)init;
- (id)initWithServiceContext:(id)context;
- (id)initWithPersistenceURL:(id)url;
- (void)clearCachedData;
- (void)modifyUserOverrides:(id /* block */)overrides;
- (void)handleUpdatedRuntimeMap:(id)map userOverrides:(id)overrides;
- (void)_withLock_saveState;
- (void)_withLock_invalidateCache;
- (id)runtimeLookupKeyForRuntimeIdentifier:(id)identifier evaluateForUncached:(id /* block */)uncached;

@end

#endif /* SimRuntimeMapData_h */
