//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.645, BuildCommit: 6e9f98c9dbaacd42e09240f9386168f3b8317f96)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14, SDK: 16, Tool: ld (1215)
//    - LC_SOURCE_VERSION: 1031.0.0.0.0
//
#ifndef SimServiceContext_h
#define SimServiceContext_h
@import Foundation;

#include "OS_xpc_object-Protocol.h"
#include "SimNotificationManagerToken.h"
#include "SimProfilesPathMonitor.h"

@class NSArray, NSDate, NSDictionary, NSMutableArray, NSMutableDictionary, NSObject, NSString, SimDeviceSet, SimDeviceType, SimRuntime;
@protocol OS_dispatch_queue;

@interface SimServiceContext : NSObject {
    /* instance variables */
    NSMutableArray *_sortedUniqueDeviceTypes;
    NSMutableDictionary *_allDeviceSets;
    NSMutableDictionary *_supportedChromeBundles;
    NSMutableDictionary *_supportedUserInterfaceBundles;
}

@property (readonly, nonatomic) NSDictionary * _Nullable preferredRuntimeBuildBySDKBuild;
@property (readonly, nonatomic) NSDictionary * _Nullable userOverriddenRuntimeBuilds;
@property (retain, nonatomic) NSObject<OS_xpc_object> * _Nullable serviceConnection;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> * _Nullable serviceConnectionQueue;
@property (retain, nonatomic) NSDate * _Nullable lastConnectionTime;
@property (nonatomic) long long connectionType;
@property (retain, nonatomic) SimProfilesPathMonitor * _Nullable profileMonitor;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> * _Nullable profileQueue;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> * _Nullable volumeNotificationQueue;
@property (nonatomic) _Bool initialized;
@property (nonatomic) _Bool valid;
@property (retain, nonatomic) NSString * _Nullable invalidationReason;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> * _Nullable allDeviceSetsQueue;
@property (retain, nonatomic) NSString * _Nullable developerDir;
@property (retain, nonatomic) SimNotificationManagerToken * _Nullable volumeNotificationToken;
@property (readonly, nonatomic) NSArray<SimDeviceType *> * _Nullable supportedDeviceTypes;
@property (readonly, nonatomic) NSDictionary<NSString *, SimDeviceType *> * _Nullable supportedDeviceTypesByIdentifier;
@property (readonly, nonatomic) NSDictionary * _Nullable supportedDeviceTypesByAlias;
@property (readonly, nonatomic) NSArray<SimRuntime *> * _Nullable supportedRuntimes;
@property (readonly, nonatomic) NSDictionary<NSString *, SimRuntime *> * _Nullable supportedRuntimesByIdentifier;
@property (readonly, nonatomic) NSDictionary * _Nullable supportedRuntimesByAlias;

/* class methods */
+ (_Nullable id)runtimesMatchingOptions:(_Nullable id)options supportedRuntimes:(_Nullable id)runtimes;
+ (_Nullable id)serviceVersionString;
+ (_Bool)currentProcessIsServer;
+ (void)_withSharedServiceContexts:(_Nullable id /* block */)contexts;
+ (_Nullable id)standaloneConnectionWithError:(id _Nullable * _Nullable)error;
+ (_Nullable id)loggingConnection;
+ (nullable SimServiceContext *)sharedServiceContextForDeveloperDir:(nonnull NSString *)dir error:(NSError * _Nullable * _Nullable)error;
+ (nullable SimServiceContext *)serviceContextForDeveloperDir:(nonnull NSString *)dir error:(NSError * _Nullable * _Nullable)error;
+ (nullable SimServiceContext *)serviceContextForDeveloperDir:(nonnull NSString *)dir connectionType:(long long)type error:(NSError * _Nullable * _Nullable)error;
+ (_Bool)loadCoreSimulatorServiceWithError:(id _Nullable * _Nullable)error;
+ (_Nullable id)_serverConnectionWithQueue:(_Nullable id)queue lastConnectionTime:(id _Nullable * _Nullable)time eventHandler:(_Nullable id /* block */)handler error:(id _Nullable * _Nullable)error;

/* instance methods */
- (_Nullable id)runtimesMatchingOptions:(_Nullable id)options;
- (_Nullable id)_optionsForPlatformPath:(_Nullable id)path sdkPath:(_Nullable id)path allowingFallbacks:(_Bool)fallbacks matchingInternalState:(_Bool)state;
- (_Nullable id)runtimeMatchingPlatformPath:(_Nullable id)path sdkPath:(_Nullable id)path error:(id _Nullable * _Nullable)error;
- (_Nullable id)runtimesExactlyMatchingPlatformPath:(_Nullable id)path sdkPath:(_Nullable id)path;
- (_Nullable id)runtimeMapData;
- (_Nullable id)_normalizeSDKCanonicalName:(_Nullable id)name;
- (_Nullable id)_knownPlatformsAndSDKsWithError:(id _Nullable * _Nullable)error;
- (_Nullable id)runtimeIdentifiersForKnownSDKs;
- (_Nullable id)_loadPlatformsAndSDKsFromDeveloperDir:(_Nullable id)dir error:(id _Nullable * _Nullable)error;
- (_Nullable id)findSDKCanonicalNamesForCurrentDeveloperDirWithError:(id _Nullable * _Nullable)error;
- (_Nullable id)findSDKCanonicalNamesForDeveloperDir:(_Nullable id)dir error:(id _Nullable * _Nullable)error;
- (void)_sendAvailabilityChangedNotification;
- (_Bool)setPreferredRuntimeBuildBySDKBuild:(_Nullable id)sdkbuild error:(id _Nullable * _Nullable)error;
- (_Bool)setUserOverrideForSDK:(_Nullable id)sdk withSDKBuild:(_Nullable id)sdkbuild useRuntimeBuild:(_Nullable id)build error:(id _Nullable * _Nullable)error;
- (_Nullable id)userOverriddenRuntimeBuildsForSDK:(_Nullable id)sdk;
- (_Nullable id)_evaluateMatchingPolicyForPlatform:(_Nullable id)platform sdk:(_Nullable id)sdk preferredMap:(_Nullable id)map userOverrides:(_Nullable id)overrides runtimesByAlias:(_Nullable id)alias bundledRuntimes:(_Nullable id)runtimes;
- (_Nullable id)_bundledRuntimes;
- (_Nullable id)_evaluateRuntimeBuildsForPlatforms:(_Nullable id)platforms withPreferredMap:(_Nullable id)map userOverrides:(_Nullable id)overrides error:(id _Nullable * _Nullable)error;
- (_Nullable id)evaluateRuntimeBuildsForCurrentDeveloperDirWithError:(id _Nullable * _Nullable)error;
- (_Nullable id)evaluateRuntimeBuildsForDeveloperDir:(_Nullable id)dir error:(id _Nullable * _Nullable)error;
- (_Nullable id)_runtimeMatchingSystemPolicyForIdentifier:(_Nullable id)identifier;
- (void)_runtimeMatchingRuntimesUpdated;
- (void)handleXPCGetRuntimeMapRequest:(_Nullable id)request;
- (void)handleXPCSetPreferredRuntimeMapRequest:(_Nullable id)request;
- (void)handleXPCSetRuntimeMapOverrideRequest:(_Nullable id)request;
- (void)handleXPCNotificationRuntimeMapUpdated:(_Nullable id)updated;
- (void)_serverRegisterSendNotificationBlock:(_Nullable id /* block */)block;
- (void)_sendNotification:(_Nullable id)notification;
- (_Nullable id)initWithDeveloperDir:(_Nullable id)dir connectionType:(long long)type error:(id _Nullable * _Nullable)error;
- (_Bool)connectWithError:(id _Nullable * _Nullable)error;
- (void)dealloc;
- (nullable SimDeviceSet *)defaultDeviceSetWithError:(NSError * _Nullable * _Nullable)error;
- (_Nullable id)_defaultDeviceSetIfLoaded;
- (nullable SimDeviceSet *)deviceSetWithPath:(nonnull NSString *)path error:(NSError * _Nullable * _Nullable)error;
- (void)_onQueue_removeDeviceSetMatchingVolumeURL:(_Nullable id)url completionGroup:(_Nullable id)group deviceSetUnloadedHandler:(_Nullable id /* block */)handler deviceShutdownHandler:(_Nullable id /* block */)handler;
- (_Nullable id)allDeviceSets;
- (void)addProfilesAtPath:(_Nullable id)path;
- (void)serviceAddProfilesAtPath:(_Nullable id)path;
- (_Bool)supportedDeviceTypesAddProfilesAtPath:(_Nullable id)path createDefaultDevicesIfNeeded:(_Bool)needed;
- (_Bool)_onQueue_addSupportedDeviceType:(_Nullable id)type;
- (void)_onQueue_regenerateDeviceTypeDictionaries;
- (_Bool)_supportedDeviceTypesAddProfilesAtPath:(_Nullable id)path createDefaultDevicesIfNeeded:(_Bool)needed allowRescan:(_Bool)rescan;
- (_Nullable id)_loadDeviceTypeProfilesAtPath:(_Nullable id)path skippingLoadedDeviceTypes:(_Nullable id)types shouldRescan:(_Bool * _Nullable)rescan;
- (_Nullable id)_onQueue_removeDeviceTypeProfilesMatchingVolumeURL:(_Nullable id)url;
- (_Bool)_onQueue_removeDeletedDeviceTypes;
- (void)_onQueue_removeDeviceTypeFromAllCollections:(_Nullable id)collections;
- (_Nullable id)_loadRuntimeProfilesAtPath:(_Nullable id)path skippingLoadedRuntimes:(_Nullable id)runtimes shouldRescan:(_Bool * _Nullable)rescan;
- (_Bool)_onQueue_addSupportedRuntime:(_Nullable id)runtime;
- (void)_onQueue_regenerateRuntimeDictionariesWithReason:(_Nullable id)reason;
- (_Bool)supportedRuntimesAddProfilesAtPath:(_Nullable id)path createDefaultDevicesIfNeeded:(_Bool)needed;
- (_Bool)_supportedRuntimesAddProfilesAtPath:(_Nullable id)path createDefaultDevicesIfNeeded:(_Bool)needed allowRescan:(_Bool)rescan;
- (_Bool)_onQueue_removeDeletedRuntimes;
- (void)_onQueue_removeRuntimeFromAllCollections:(_Nullable id)collections;
- (_Nullable id)_onQueue_removeRuntimeProfilesMatchingVolumeURL:(_Nullable id)url;
- (_Nullable id)_onQueue_addProfilesForVolumeURL:(_Nullable id)url;
- (void)addProfilesForDeveloperDir:(_Nullable id)dir;
- (void)handleReconnectionBookkeeping;
- (void)handleXPCEvent:(_Nullable id)xpcevent;
- (void)sendRequest:(_Nullable id)request;
- (_Bool)sendRequest:(_Nullable id)request reply:(id _Nullable * _Nullable)reply error:(id _Nullable * _Nullable)error;
- (_Bool)shouldLoadUIBundles;
- (void)supportedChromeBundlesAddProfilesAtPath:(_Nullable id)path;
- (void)supportedUserInterfaceBundlesAddProfilesAtPath:(_Nullable id)path;
- (void)_supportedBundlesAddProfilesAtPath:(_Nullable id)path withSuffix:(_Nullable id)suffix storage:(_Nullable id)storage loadBundle:(_Bool)bundle logDescription:(_Nullable id)description;
- (_Nullable id)supportedChromeProfileBundles;
- (_Nullable id)supportedUserInterfaceProfileBundles;
- (_Nullable id)_supportedBundlesFrom:(_Nullable id)from;
- (_Nullable id)_onQueue_removeChromeBundlesMatchingVolumeURL:(_Nullable id)url;
- (_Nullable id)_onQueue_removeUserInterfaceBundlesMatchingVolumeURL:(_Nullable id)url;
- (_Nullable id)_onQueue_removeBundles:(_Nullable id)bundles matchingVolumeURL:(_Nullable id)url;
- (_Nullable id)_loadProfilesAtPath:(_Nullable id)path bundleSuffix:(_Nullable id)suffix classForBundle:(_Nullable Class)bundle skippingLoadedProfiles:(_Nullable id)profiles shouldRescan:(_Bool * _Nullable)rescan;
- (void)ensureProfilesLoadedForRuntimeBundleURL:(_Nullable id)url deviceTypeBundleURL:(_Nullable id)url completionQueue:(_Nullable id)queue completionHandler:(_Nullable id /* block */)handler;

@end

#endif /* SimServiceContext_h */
