//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.645, BuildCommit: 6e9f98c9dbaacd42e09240f9386168f3b8317f96)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14, SDK: 16, Tool: ld (1215)
//    - LC_SOURCE_VERSION: 1031.0.0.0.0
//
#ifndef SimAudioHostRouteDescriptorState_h
#define SimAudioHostRouteDescriptorState_h
@import Foundation;

#include "SimAudioDescriptorState-Protocol.h"

@class NSObject, NSString;
@protocol OS_dispatch_queue;

@interface SimAudioHostRouteDescriptorState : NSObject <SimAudioDescriptorState>

@property (nonatomic) int powerState;
@property (nonatomic) NSString *guestDataPath;
@property (readonly, nonatomic) NSObject<OS_dispatch_queue> *memoizableSerializerQueue;
@property (readonly) NSUInteger hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, nonatomic) NSString *portIdentifier;

/* class methods */
+ (id)defaultAudioDescriptorStateWithPowerState:(int)state guestDataPath:(id)path;

/* instance methods */

@end

#endif /* SimAudioHostRouteDescriptorState_h */
