//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.645, BuildCommit: 6e9f98c9dbaacd42e09240f9386168f3b8317f96)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14, SDK: 16, Tool: ld (1215)
//    - LC_SOURCE_VERSION: 1031.0.0.0.0
//
#ifndef SimDeviceIODeviceTypeInterface_Protocol_h
#define SimDeviceIODeviceTypeInterface_Protocol_h
@import Foundation;
@import CoreGraphics;

#include "ROCKMemoizable-Protocol.h"

@class NSDictionary, NSString, NSURL;

@protocol SimDeviceIODeviceTypeInterface <ROCKMemoizable>

@required

@property (readonly, nonatomic) NSString *name;
@property (readonly, nonatomic) NSString *identifier;
@property (readonly, nonatomic) NSDictionary *capabilities;
@property (readonly, nonatomic) NSURL *framebufferMaskURL;
@property (readonly, nonatomic) NSString *chromeIdentifier;
@property (readonly, nonatomic) float mainScreenScale;
@property (readonly, nonatomic) CGSize mainScreenSize;
@property (readonly, nonatomic) CGSize mainScreenDPI;
@property (readonly, nonatomic) unsigned int mainScreenColorspace;
@property (readonly, nonatomic) CGSize defaultCanvasSize;
@property (readonly, nonatomic) unsigned int minRuntimeVersion;
@property (readonly, nonatomic) unsigned int maxRuntimeVersion;
@property (readonly, nonatomic) NSURL *bundleURL;

/* required instance methods */
- (_Bool)supportsFeature:(id)feature;
- (_Bool)supportsFeatureConditionally:(id)conditionally;

@optional

@end

#endif /* SimDeviceIODeviceTypeInterface_Protocol_h */
