//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.645, BuildCommit: 6e9f98c9dbaacd42e09240f9386168f3b8317f96)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14, SDK: 16, Tool: ld (1215)
//    - LC_SOURCE_VERSION: 1031.0.0.0.0
//
#ifndef SimDeviceNotificationManager_h
#define SimDeviceNotificationManager_h
@import Foundation;

#include "SimDeviceNotifier-Protocol.h"

@class NSMutableDictionary, NSObject;
@protocol OS_dispatch_queue;

@interface SimDeviceNotificationManager : NSObject <SimDeviceNotifier>

@property (retain, nonatomic) NSObject<OS_dispatch_queue> *handlersQueue;
@property (retain, nonatomic) NSMutableDictionary *handlers;
@property (nonatomic) unsigned long long next_regID;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> *sendQueue;

/* instance methods */
- (id)init;
- (unsigned long long)registerNotificationHandlerOnQueue:(id)queue handler:(id /* block */)handler;
- (_Bool)unregisterNotificationHandler:(unsigned long long)handler error:(id *)error;
- (void)sendNotification:(id)notification;
- (void)sendNotification:(id)notification completionQueue:(id)queue completionBlock:(id /* block */)block;

@end

#endif /* SimDeviceNotificationManager_h */
