//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.645, BuildCommit: 6e9f98c9dbaacd42e09240f9386168f3b8317f96)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14, SDK: 16, Tool: ld (1215)
//    - LC_SOURCE_VERSION: 1031.0.0.0.0
//
#ifndef SimDevice_h
#define SimDevice_h
@import Foundation;
@import CoreGraphics;

#include "OS_xpc_object-Protocol.h"
#include "SimDeviceBootInfo.h"
#include "SimDeviceIOProtocol-Protocol.h"
#include "SimDeviceNotificationManager.h"
#include "SimDeviceNotifier-Protocol.h"
#include "SimDeviceSet.h"
#include "SimDeviceType.h"
#include "SimLaunchHostClient.h"
#include "SimRuntime.h"

@class AXPTranslatorRequest;
@class AXPTranslatorResponse;
@class NSArray, NSDate, NSDictionary, NSMutableArray, NSMutableDictionary, NSObject, NSString, NSUUID, SimDevicePasteboard, SimMachPort;
@protocol OS_dispatch_queue, OS_dispatch_source;

@interface SimDevice : NSObject <SimDeviceNotifier> {
    /* instance variables */
    SimDeviceBootInfo *_bootStatus;
    SimMachPort *_hostSupportPort;
    _Bool _isEphemeral;
}

@property (copy, nonatomic) NSString * _Nullable deviceTypeIdentifier;
@property (copy, nonatomic) NSUUID * _Nullable UDID;
@property (weak, nonatomic) SimDeviceSet * _Nullable deviceSet;
@property (nonatomic) _Bool isDeleted;
@property (readonly, nonatomic) NSString * _Nullable logPath;
@property (retain, nonatomic) SimDeviceNotificationManager * _Nullable notificationManager;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> * _Nullable bootstrapQueue;
@property (retain, nonatomic) NSMutableDictionary * _Nullable registeredServices;
@property (retain, nonatomic) NSMutableDictionary * _Nullable registeredXPCServices;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> * _Nullable stateVariableQueue;
@property (retain, nonatomic) NSUUID * _Nullable bootSessionUUID;
@property (retain) SimDeviceType * _Nullable deviceTypeOverride;
@property (retain) SimRuntime * _Nullable runtimeOverride;
@property (nonatomic) unsigned long long runtimePolicy;
@property (copy, nonatomic) NSString * _Nullable runtimeSpecifier;
@property (nonatomic) _Atomic unsigned long long bootGeneration;
@property (readonly, nonatomic) NSArray * _Nullable launchDaemonsPaths;
@property (retain, nonatomic) SimDevicePasteboard * _Nullable pasteboard;
@property (nonatomic) unsigned long long validationRetryNotificationRegistrationID;
@property (retain, nonatomic) NSObject<OS_dispatch_source> * _Nullable bootMonitorTimer;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> * _Nullable bootMonitorQueue;
@property (retain, nonatomic) NSDate * _Nullable bootStartedAt;
@property (retain, nonatomic) NSDictionary * _Nullable providerEnvironmentVars;
@property (readonly, nonatomic) SimLaunchHostClient * _Nullable launchHostClient;
@property (retain, nonatomic) NSObject<OS_xpc_object> * _Nullable accessibilityConnection;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> * _Nullable notificationProxyQueue;
@property (retain, nonatomic) NSMutableArray * _Nullable darwinNotificationTokens;
@property (copy, nonatomic) NSDictionary * _Nullable bootEnvironmentExtra;
@property (readonly, nonatomic, nullable) SimDeviceType * deviceType;
@property (readonly, nonatomic, nullable) SimRuntime * runtime;
@property (readonly, nonatomic, nullable) NSString * runtimeIdentifier;
@property (readonly, nonatomic) unsigned long long state;
@property (readonly, nonatomic, nullable) NSString * stateString;
@property (readonly, nonatomic) NSString * _Nullable name;
@property (readonly, nonatomic) NSString * _Nullable descriptiveName;
@property (readonly, nonatomic) NSArray * _Nullable supportedArchs;
@property (readonly, nonatomic) NSArray * _Nullable supportedArchStrings;
@property (readonly, nonatomic) NSArray * _Nullable deviceSets;
@property (readonly, nonatomic) NSDate * _Nullable lastBootedAt;
@property (readonly, nonatomic) _Bool available;
@property (retain, nonatomic) _Nullable id <SimDeviceIOProtocol> io;

/* class methods */
+ (_Nullable id)createDeviceWithName:(_Nullable id)name deviceSet:(_Nullable id)set deviceType:(_Nullable id)type runtime:(_Nullable id)runtime initialDataPath:(_Nullable id)path error:(id _Nullable * _Nullable)error;
+ (_Nullable id)simDeviceAtPath:(_Nullable id)path deviceSet:(_Nullable id)set;
+ (_Nullable id)simDevice:(_Nullable id)device UDID:(_Nullable id)udid deviceTypeIdentifier:(_Nullable id)identifier runtimeIdentifier:(_Nullable id)identifier runtimePolicy:(unsigned long long)policy runtimeSpecifier:(_Nullable id)specifier state:(unsigned long long)state lastBootedAt:(_Nullable id)at deviceSet:(_Nullable id)set;
+ (_Bool)isValidState:(unsigned long long)state;
+ (_Bool)supportsFeature:(_Nullable id)feature deviceType:(_Nullable id)type runtime:(_Nullable id)runtime;
+ (_Nullable id)_xpcMessageWithAXRequest:(_Nullable id)axrequest;
+ (_Nullable id)_axResponseFromXPCMessage:(_Nullable id)xpcmessage;

/* instance methods */
- (long long)currentUIInterfaceStyle;
- (_Bool)setUIInterfaceStyle:(long long)style error:(NSError * _Nullable * _Nullable)error;
- (_Bool)setPrivacyAccessForService:(_Nullable id)service bundleID:(_Nullable id)id granted:(_Bool)granted error:(id _Nullable * _Nullable)error;
- (_Bool)resetPrivacyAccessForService:(_Nullable id)service bundleID:(_Nullable id)id error:(id _Nullable * _Nullable)error;
- (_Bool)connectIDSRelayToDevice:(_Nullable id)device disconnectMonitorPort:(unsigned int * _Nullable)port error:(id _Nullable * _Nullable)error;
- (_Bool)disconnectIDSRelayToDevice:(_Nullable id)device error:(id _Nullable * _Nullable)error;
- (_Bool)setActiveIDSRelayDevice:(_Nullable id)device error:(id _Nullable * _Nullable)error;
- (_Bool)unpairIDSRelayWithDevice:(_Nullable id)device error:(id _Nullable * _Nullable)error;
- (_Bool)setDisplayBacklightActive:(_Bool)active error:(id _Nullable * _Nullable)error;
- (_Nullable id)availableLocationScenarios;
- (_Bool)clearSimulatedLocationWithError:(id _Nullable * _Nullable)error;
- (_Bool)setLocationScenario:(_Nullable id)scenario error:(id _Nullable * _Nullable)error;
- (_Bool)setLocationScenarioWithPath:(_Nullable id)path error:(id _Nullable * _Nullable)error;
- (_Bool)setLocationWithLatitude:(double)latitude andLongitude:(double)longitude error:(id _Nullable * _Nullable)error;
- (_Bool)startLocationSimulationWithDistance:(double)distance speed:(double)speed waypoints:(_Nullable id)waypoints error:(id _Nullable * _Nullable)error;
- (_Bool)startLocationSimulationWithInterval:(double)interval speed:(double)speed waypoints:(_Nullable id)waypoints error:(id _Nullable * _Nullable)error;
- (_Bool)_startLocationSimulationWithDistance:(double)distance interval:(double)interval speed:(double)speed waypoints:(_Nullable id)waypoints error:(id _Nullable * _Nullable)error;
- (_Bool)_sendStatusBarOverrideDict:(_Nullable id)dict error:(id _Nullable * _Nullable)error;
- (_Bool)overrideStatusBarTimeString:(_Nullable id)string error:(id _Nullable * _Nullable)error;
- (_Bool)overrideStatusBarDataNetworkType:(unsigned long long)type error:(id _Nullable * _Nullable)error;
- (_Bool)overrideStatusBarWiFiMode:(unsigned long long)mode bars:(unsigned long long)bars error:(id _Nullable * _Nullable)error;
- (_Bool)overrideStatusBarCellularMode:(unsigned long long)mode operatorName:(_Nullable id)name bars:(unsigned long long)bars error:(id _Nullable * _Nullable)error;
- (_Bool)overrideStatusBarBatteryState:(unsigned long long)state batteryLevel:(unsigned long long)level showNotCharging:(_Bool)charging error:(id _Nullable * _Nullable)error;
- (_Bool)clearStatusBarOverrides:(unsigned long long)overrides error:(id _Nullable * _Nullable)error;
- (_Bool)currentStatusBarOverridesForTimeString:(id _Nullable * _Nullable)string dataNetworkType:(id _Nullable * _Nullable)type wiFiMode:(id _Nullable * _Nullable)mode wiFiBars:(id _Nullable * _Nullable)bars cellularMode:(id _Nullable * _Nullable)mode operatorName:(id _Nullable * _Nullable)name cellularBars:(id _Nullable * _Nullable)bars batteryState:(id _Nullable * _Nullable)state batteryLevel:(id _Nullable * _Nullable)level showNotCharging:(id _Nullable * _Nullable)charging error:(id _Nullable * _Nullable)error;
- (_Bool)getCADebugOption:(unsigned int)option;
- (void)setCADebugOption:(unsigned int)option enabled:(_Bool)enabled;
- (_Bool)updateNearbyInteractionDeviceRect:(CGRect)rect deviceRotation:(double)rotation error:(id _Nullable * _Nullable)error;
- (void)bootAsyncWithOptions:(_Nullable id)options completionHandler:(_Nullable id /* block */)handler;
- (void)shutdownAsyncWithCompletionHandler:(_Nullable id /* block */)handler;
- (void)renameAsync:(_Nullable id)async completionHandler:(_Nullable id /* block */)handler;
- (void)eraseContentsAndSettingsAsyncWithCompletionHandler:(_Nullable id /* block */)handler;
- (void)restoreContentsAndSettingsAsyncFromDevice:(_Nullable id)device completionHandler:(_Nullable id /* block */)handler;
- (void)spawnAsyncWithPath:(_Nullable id)path options:(_Nullable id)options terminationHandler:(_Nullable id /* block */)handler completionHandler:(_Nullable id /* block */)handler;
- (int)spawnWithPath:(_Nullable id)path options:(_Nullable id)options terminationHandler:(_Nullable id /* block */)handler error:(id _Nullable * _Nullable)error;
- (void)launchApplicationAsyncWithID:(_Nullable id)id options:(_Nullable id)options completionHandler:(_Nullable id /* block */)handler;
- (void)triggerCloudSyncWithCompletionHandler:(_Nullable id /* block */)handler;
- (long long)currentIncreaseContrastMode;
- (_Bool)setIncreaseContrastEnabled:(_Bool)enabled error:(id _Nullable * _Nullable)error;
- (long long)currentContentSizeCategory;
- (_Bool)setContentSizeCategory:(long long)category error:(id _Nullable * _Nullable)error;
- (_Bool)isOSFeatureEnabled:(_Nullable id)enabled domain:(_Nullable id)domain;
- (_Bool)addCertificateAtURL:(_Nullable id)url trustAsRoot:(_Bool)root error:(id _Nullable * _Nullable)error;
- (_Bool)resetKeychainWithError:(id _Nullable * _Nullable)error;
- (_Bool)sendPushNotificationForBundleID:(_Nullable id)id jsonPayload:(_Nullable id)payload error:(id _Nullable * _Nullable)error;
- (_Nullable id)initDevice:(_Nullable id)device UDID:(_Nullable id)udid deviceTypeIdentifier:(_Nullable id)identifier runtimeIdentifier:(_Nullable id)identifier runtimePolicy:(unsigned long long)policy runtimeSpecifier:(_Nullable id)specifier state:(unsigned long long)state initialDataPath:(_Nullable id)path preparingForDeletion:(_Bool)deletion isEphemeral:(_Bool)ephemeral lastBootedAt:(_Nullable id)at deviceSet:(_Nullable id)set;
- (void)_mergeProviderEnvironmentVars:(_Nullable id)vars;
- (void)_onBootstrapQueue_notifyDeviceIOBooted;
- (_Bool)_onBootstrapQueue_initializeDeviceIO:(id _Nullable * _Nullable)io;
- (void)dealloc;
- (_Nullable id)description;
- (_Nullable id)debugDescription;
- (void)validateAndFixStateUsingInitialDataPath:(_Nullable id)path;
- (_Bool)setRuntimePolicy:(unsigned long long)policy withRuntimeSpecifier:(_Nullable id)specifier error:(id _Nullable * _Nullable)error;
- (void)_setRuntimePolicy:(unsigned long long)policy withRuntimeSpecifier:(_Nullable id)specifier;
- (_Bool)_findSimRuntimeWithPolicyBlock:(_Nullable id /* block */)block policyName:(_Nullable id)name context:(_Nullable id)context runtimeSpecifier:(_Nullable id)specifier error:(id _Nullable * _Nullable)error;
- (_Nullable id)saveStateDict;
- (void)saveToDisk;
- (_Nullable id)launchdJobName;
- (_Bool)supportsFeature:(_Nullable id)feature;
- (_Bool)ensureRequiredPathsWithError:(id _Nullable * _Nullable)error;
- (_Bool)clearTmpWithError:(id _Nullable * _Nullable)error;
- (_Bool)createDarwinNotificationProxy:(_Nullable id)proxy toSimAs:(_Nullable id)as withState:(_Bool)state error:(id _Nullable * _Nullable)error;
- (_Bool)createDarwinNotificationProxiesWithError:(id _Nullable * _Nullable)error;
- (_Bool)createOverlayLaunchdPlistsFromFilesInDirectory:(_Nullable id)directory executableRoot:(_Nullable id)root error:(id _Nullable * _Nullable)error;
- (_Bool)createOverlayLaunchdPlistsWithError:(id _Nullable * _Nullable)error;
- (_Bool)recordUsageWithArch:(_Nullable id)arch error:(id _Nullable * _Nullable)error;
- (_Bool)createLaunchdJobWithBinpref:(_Nullable id)binpref extraEnvironment:(_Nullable id)environment disabledJobs:(_Nullable id)jobs error:(id _Nullable * _Nullable)error;
- (_Bool)removeLaunchdJobWithError:(id _Nullable * _Nullable)error;
- (_Nullable id)portsToRegisterWithLaunchd;
- (_Bool)startLaunchdWithDeathPort:(_Nullable id)port error:(id _Nullable * _Nullable)error;
- (void)bootAsyncWithOptions:(_Nullable id)options completionQueue:(_Nullable id)queue completionHandler:(_Nullable id /* block */)handler;
- (_Bool)bootWithOptions:(_Nullable id)options error:(NSError * _Nullable * _Nullable)error;
- (_Bool)_onBootstrapQueue_bootWithOptions:(_Nullable id)options error:(id _Nullable * _Nullable)error;
- (_Bool)_onBootstrapQueue_bootWithOptions:(_Nullable id)options deathMonitorPort:(_Nullable id)port error:(id _Nullable * _Nullable)error;
- (void)_onBootMonitorQueue_bootStatusTimerFired;
- (_Bool)_sendBridgeRequest:(_Nullable id /* block */)request caller:(_Nullable SEL)caller error:(id _Nullable * _Nullable)error;
- (_Bool)_sendBridgeRequest:(_Nullable id /* block */)request caller:(_Nullable SEL)caller operationDescription:(_Nullable id)description error:(id _Nullable * _Nullable)error;
- (void)_shutdownIfProfilesOrDataURLsOnVolume:(_Nullable id)volume completionGroup:(_Nullable id)group deviceShutdownHandler:(_Nullable id /* block */)handler;
- (void)shutdownAsyncWithCompletionQueue:(_Nullable id)queue completionHandler:(_Nullable id /* block */)handler;
- (_Bool)shutdownWithError:(NSError * _Nullable * _Nullable)error;
- (_Bool)_onBootstrapQueue_shutdownWithError:(id _Nullable * _Nullable)error;
- (_Bool)_onBootstrapQueue_shutdownIOAndNotifyWithError:(id _Nullable * _Nullable)error;
- (void)_executeOnBootstrapQueue:(_Nullable id /* block */)queue;
- (void)_forDeviceIO_assertBootstrapQueue;
- (void)renameAsync:(_Nullable id)async completionQueue:(_Nullable id)queue completetionHandler:(_Nullable id /* block */)handler;
- (_Bool)rename:(_Nullable id)rename error:(id _Nullable * _Nullable)error;
- (_Bool)_onBootstrapQueue_rename:(_Nullable id)queue_rename error:(id _Nullable * _Nullable)error;
- (_Bool)prepareForDeletionWithError:(id _Nullable * _Nullable)error;
- (_Bool)_onBootstrapQueue_prepareForDeletionWithError:(id _Nullable * _Nullable)error;
- (void)upgradeAsyncToRuntime:(_Nullable id)runtime completionQueue:(_Nullable id)queue completionHandler:(_Nullable id /* block */)handler;
- (_Bool)upgradeToRuntime:(_Nullable id)runtime error:(id _Nullable * _Nullable)error;
- (_Bool)_onBootstrapQueue_upgradeToRuntime:(_Nullable id)runtime error:(id _Nullable * _Nullable)error;
- (void)eraseContentsAndSettingsAsyncWithCompletionQueue:(_Nullable id)queue completionHandler:(_Nullable id /* block */)handler;
- (_Bool)eraseContentsAndSettingsWithError:(id _Nullable * _Nullable)error;
- (_Bool)_onBootstrapQueue_eraseContentsAndSettingsUsingInitialDataPath:(_Nullable id)path error:(id _Nullable * _Nullable)error;
- (void)restoreContentsAndSettingsAsyncFromDevice:(_Nullable id)device completionQueue:(_Nullable id)queue completionHandler:(_Nullable id /* block */)handler;
- (_Bool)restoreContentsAndSettingsFromDevice:(_Nullable id)device error:(id _Nullable * _Nullable)error;
- (_Bool)_onBootstrapQueue_restoreContentsAndSettingsFromDevice:(_Nullable id)device error:(id _Nullable * _Nullable)error;
- (_Nullable id)getenv:(_Nullable id)getenv error:(id _Nullable * _Nullable)error;
- (unsigned int)lookup:(_Nullable id)lookup error:(id _Nullable * _Nullable)error;
- (_Bool)_registerPort:(unsigned int)port service:(_Nullable id)service error:(id _Nullable * _Nullable)error;
- (_Bool)_registerSimMachPort:(_Nullable id)port service:(_Nullable id)service error:(id _Nullable * _Nullable)error;
- (_Bool)_sendRegisterPortRequestForPort:(unsigned int)port service:(_Nullable id)service serviceContext:(_Nullable id)context error:(id _Nullable * _Nullable)error;
- (_Bool)registerPort:(unsigned int)port service:(_Nullable id)service error:(id _Nullable * _Nullable)error;
- (_Bool)_unregisterService:(_Nullable id)service error:(id _Nullable * _Nullable)error;
- (_Bool)unregisterService:(_Nullable id)service error:(id _Nullable * _Nullable)error;
- (_Bool)registerXPCServiceName:(_Nullable id)name peerHandlerQueue:(_Nullable id)queue peerHandler:(_Nullable id /* block */)handler error:(id _Nullable * _Nullable)error;
- (_Bool)unregisterXPCServiceName:(_Nullable id)name error:(id _Nullable * _Nullable)error;
- (void)spawnAsyncWithPath:(_Nullable id)path options:(_Nullable id)options terminationQueue:(_Nullable id)queue terminationHandler:(_Nullable id /* block */)handler completionQueue:(_Nullable id)queue completionHandler:(_Nullable id /* block */)handler;
- (int)spawnWithPath:(_Nullable id)path options:(_Nullable id)options terminationQueue:(_Nullable id)queue terminationHandler:(_Nullable id /* block */)handler error:(id _Nullable * _Nullable)error;
- (_Bool)spawnWithPath:(_Nullable id)path options:(_Nullable id)options terminationQueue:(_Nullable id)queue terminationHandler:(_Nullable id /* block */)handler pid:(int * _Nullable)pid error:(id _Nullable * _Nullable)error;
- (int)_onBootstrapQueue_spawnWithPath:(_Nullable id)path options:(_Nullable id)options terminationQueue:(_Nullable id)queue terminationHandler:(_Nullable id /* block */)handler error:(id _Nullable * _Nullable)error;
- (int)_spawnFromLaunchdWithPath:(_Nullable id)path options:(_Nullable id)options terminationQueue:(_Nullable id)queue terminationHandler:(_Nullable id /* block */)handler error:(id _Nullable * _Nullable)error;
- (int)_spawnFromSelfWithPath:(_Nullable id)path options:(_Nullable id)options terminationQueue:(_Nullable id)queue terminationHandler:(_Nullable id /* block */)handler error:(id _Nullable * _Nullable)error;
- (_Nullable id)environment;
- (_Nullable id)devicePath;
- (_Nullable id)dataPath;
- (_Nullable id)memoryWarningFilePath;
- (void)simulateMemoryWarning;
- (unsigned long long)registerNotificationHandlerOnQueue:(_Nullable id)queue handler:(_Nullable id /* block */)handler;
- (_Bool)unregisterNotificationHandler:(unsigned long long)handler error:(id _Nullable * _Nullable)error;
- (void)setState:(unsigned long long)state lastBootedAt:(_Nullable id)at;
- (_Nullable id)bootStatus;
- (void)setBootStatus:(_Nullable id)status;
- (_Bool)isEphemeral;
- (void)setIsEphemeral:(_Bool)ephemeral;
- (void)handleXPCNotification:(_Nullable id)xpcnotification;
- (void)handleXPCNotificationDeviceStateChanged:(_Nullable id)changed;
- (void)handleXPCNotificationDeviceBootStatusChanged:(_Nullable id)changed;
- (void)handleXPCRequest:(_Nullable id)xpcrequest;
- (void)handleXPCRequestRename:(_Nullable id)rename;
- (void)handleXPCRequestBoot:(_Nullable id)boot;
- (void)handleXPCRequestShutdown:(_Nullable id)shutdown;
- (void)handleXPCRequestUpgrade:(_Nullable id)upgrade;
- (void)handleXPCRequestErase:(_Nullable id)erase;
- (void)handleXPCRequestRestore:(_Nullable id)restore;
- (void)handleXPCRequestRegister:(_Nullable id)_register;
- (void)handleXPCRequestUnregister:(_Nullable id)unregister;
- (void)handleXPCRequestLookup:(_Nullable id)lookup;
- (void)handleXPCRequestGetenv:(_Nullable id)getenv;
- (void)handleXPCRequestSetRuntimePolicy:(_Nullable id)policy;
- (void)handleXPCRequestDeviceIOEnumeratePorts:(_Nullable id)ports;
- (void)handleXPCRequestUpdateNearbyInteraction:(_Nullable id)interaction;
- (_Nullable id)createXPCRequest:(_Nullable id)xpcrequest;
- (_Nullable id)createXPCNotification:(_Nullable id)xpcnotification;
- (_Nullable id)newDeviceNotification;
- (long long)compare:(_Nullable id)compare;
- (_Nullable id)hostSupportPortWithError:(id _Nullable * _Nullable)error;
- (_Bool)openURL:(_Nullable id)url error:(NSError * _Nullable * _Nullable)error;
- (_Bool)enableCarPlay:(_Bool)play error:(id _Nullable * _Nullable)error;
- (_Bool)addMedia:(_Nullable id)media error:(id _Nullable * _Nullable)error;
- (_Bool)addPhoto:(_Nullable id)photo error:(id _Nullable * _Nullable)error;
- (_Bool)addVideo:(_Nullable id)video error:(id _Nullable * _Nullable)error;
- (_Bool)setKeyboardLanguage:(_Nullable id)language error:(id _Nullable * _Nullable)error;
- (_Bool)setHardwareKeyboardEnabled:(_Bool)enabled keyboardType:(unsigned char)type error:(id _Nullable * _Nullable)error;
- (_Bool)installApplication:(_Nullable id)application withOptions:(_Nullable id)options error:(NSError * _Nullable * _Nullable)error;
- (_Bool)uninstallApplication:(_Nullable id)application withOptions:(_Nullable id)options error:(NSError * _Nullable * _Nullable)error;
- (_Bool)applicationIsInstalled:(_Nullable id)installed type:(id _Nullable * _Nullable)type error:(id _Nullable * _Nullable)error;
- (_Nullable id)propertiesOfApplication:(_Nullable id)application error:(id _Nullable * _Nullable)error;
- (_Nullable id)installedAppsWithError:(NSError * _Nullable * _Nullable)error;
- (void)launchApplicationAsyncWithID:(_Nullable id)id options:(_Nullable id)options completionQueue:(_Nullable id)queue completionHandler:(_Nullable id /* block */)handler;
- (int)launchApplicationWithID:(nonnull NSString *)id options:(nullable NSDictionary *)options error:(NSError * _Nullable * _Nullable)error;
- (_Bool)launchApplicationWithID:(nonnull NSString *)id options:(nullable NSDictionary *)options pid:(nonnull int *)pid error:(NSError * _Nullable * _Nullable)error;
- (_Bool)terminateApplicationWithID:(nonnull NSString *)id error:(NSError * _Nullable * _Nullable)error;
- (_Bool)postDarwinNotification:(_Nullable id)notification error:(id _Nullable * _Nullable)error;
- (_Bool)darwinNotificationGetState:(unsigned long long * _Nullable)state name:(_Nullable id)name error:(id _Nullable * _Nullable)error;
- (_Bool)darwinNotificationSetState:(unsigned long long)state name:(_Nullable id)name error:(id _Nullable * _Nullable)error;
- (void)triggerCloudSyncWithCompletionQueue:(_Nullable id)queue completionHandler:(_Nullable id /* block */)handler;
- (_Bool)triggerCloudSyncWithError:(id _Nullable * _Nullable)error;
- (_Bool)syncUnpairedDevicesWithError:(id _Nullable * _Nullable)error;
- (_Bool)installApplicationDataContainer:(_Nullable id)container error:(id _Nullable * _Nullable)error;
- (_Bool)isAvailableWithError:(id _Nullable * _Nullable)error;
- (_Nullable id)_onBootstrapQueue_deviceIOCreatingIfNeeded;
- (void)bootstrapQueueAsync:(_Nullable id /* block */)async completionQueue:(_Nullable id)queue completionHandler:(_Nullable id /* block */)handler;
- (_Bool)bootstrapQueueSync:(_Nullable id /* block */)sync;
- (nullable NSString *)accessibilityPlatformTranslationToken;
- (void)sendAccessibilityRequestAsync:(nonnull AXPTranslatorRequest *)request
                      completionQueue:(nonnull dispatch_queue_t)queue
                    completionHandler:(nonnull void (^)(AXPTranslatorResponse * _Nonnull))handler;

@end

#endif /* SimDevice_h */
