//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.645, BuildCommit: 6e9f98c9dbaacd42e09240f9386168f3b8317f96)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14, SDK: 16, Tool: ld (1215)
//    - LC_SOURCE_VERSION: 1031.0.0.0.0
//
#ifndef SimDiskImageManager_h
#define SimDiskImageManager_h
@import Foundation;

#include "OS_xpc_object-Protocol.h"
#include "SimDeviceNotificationManager.h"

@class NSArray, NSDictionary, NSObject, NSURL;
@protocol OS_dispatch_queue;

@interface SimDiskImageManager : NSObject {
    /* instance variables */
    NSDictionary *_cachedDiskImages;
}

@property (copy, nonatomic) NSArray *ignoredMountDirectories;
@property (copy, nonatomic) NSArray *trustedMountDirectories;
@property (nonatomic) _Bool allowUntrustedMountDirectories;
@property (retain, nonatomic) NSObject<OS_xpc_object> *connection;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> *queue;
@property (nonatomic) unsigned long long connectionState;
@property (retain, nonatomic) SimDeviceNotificationManager *notificationManager;
@property (nonatomic) unsigned long long imagesUpdatedGeneration;
@property (copy) NSURL *developerDirectory;

/* class methods */
+ (id)serviceVersionWithError:(id *)error;
+ (_Bool)askServiceToRestartIfNotVersion:(id)version error:(id *)error;
+ (_Bool)kickstartServiceWithError:(id *)error;
+ (id)sharedManager;
+ (void)_didUseRuntimeBundleAtURL:(id)url;

/* instance methods */
- (_Bool)shouldEnableInternalAuthenticationMethods;
- (id)init;
- (_Bool)_onQueue_checkConnection:(id *)connection;
- (_Bool)_checkConnectionWithErrorQueue:(id)queue errorHandler:(id /* block */)handler;
- (id)trustedMountDirectoriesWithError:(id *)error;
- (void)_onQueue_handleImagesUpdated:(id)updated;
- (void)_handleXPCEvent:(id)xpcevent;
- (_Bool)shouldLoadRuntimesAtDiskMountPoint:(id)point;
- (id)_developerDir;
- (void)listDiskImagesOnCompletionQueue:(id)queue completionHandler:(id /* block */)handler;
- (id)diskImages;
- (id)diskImagesMatchingPlatform:(id)platform;
- (unsigned long long)registerDiskImagesUpdatedHandlerOnQueue:(id)queue handler:(id /* block */)handler;
- (_Bool)unregisterDiskImagesUpdatedHandler:(unsigned long long)handler error:(id *)error;
- (void)addDiskImageAtURL:(id)url copyMoveStrategy:(unsigned long long)strategy expandPartition:(_Bool)partition userInfo:(id)info completionQueue:(id)queue completionHandler:(id /* block */)handler;
- (void)addDiskImageAtURL:(id)url copyMoveStrategy:(unsigned long long)strategy expandPartition:(_Bool)partition userInfo:(id)info certificateURL:(id)url certificateAuth:(id)auth completionQueue:(id)queue completionHandler:(id /* block */)handler;
- (void)addDiskImageAtURL:(id)url copyMoveStrategy:(unsigned long long)strategy expandPartition:(_Bool)partition userInfo:(id)info dawToken:(id)token completionQueue:(id)queue completionHandler:(id /* block */)handler;
- (void)addDiskImageAtURL:(id)url copyMoveStrategy:(unsigned long long)strategy expandPartition:(_Bool)partition alwaysPersonalize:(_Bool)personalize userInfo:(id)info dawToken:(id)token certificateURL:(id)url certificateAuth:(id)auth completionQueue:(id)queue completionHandler:(id /* block */)handler;
- (void)addDiskImageAtURL:(id)url copyMoveStrategy:(unsigned long long)strategy expandPartition:(_Bool)partition alwaysPersonalize:(_Bool)personalize mountingMode:(long long)mode userInfo:(id)info dawToken:(id)token certificateURL:(id)url certificateAuth:(id)auth completionQueue:(id)queue completionHandler:(id /* block */)handler;
- (id)_personalizationManifestFilePathForDiskImageAtURL:(id)url alwaysPersonalize:(_Bool)personalize authenticationType:(long long)type cryptexVariant:(id)variant originalImageURL:(id)url error:(id *)error;
- (void)addCredentialsToRequest:(id)request dawToken:(id)token certificateURL:(id)url certificateAuth:(id)auth;
- (void)_addDiskImageAtURL:(id)url copyMoveStrategy:(unsigned long long)strategy expandPartition:(_Bool)partition alwaysPersonalize:(_Bool)personalize mountingMode:(long long)mode userInfo:(id)info dawToken:(id)token certificateURL:(id)url certificateAuth:(id)auth completionQueue:(id)queue completionHandler:(id /* block */)handler;
- (void)_addInnerDiskImageAtURL:(id)url parentUUID:(id)uuid parentMountURL:(id)url copyMoveStrategy:(unsigned long long)strategy mountingMode:(long long)mode expandPartition:(_Bool)partition userInfo:(id)info dawToken:(id)token certificateURL:(id)url certificateAuth:(id)auth personalizationManifestURL:(id)url supportedCryptexVariant:(id)variant completionQueue:(id)queue completionHandler:(id /* block */)handler;
- (void)_mountToDetectImageBundle:(id)bundle copyMoveStrategy:(unsigned long long)strategy dawToken:(id)token certificateURL:(id)url certificateAuth:(id)auth completionQueue:(id)queue completionHandler:(id /* block */)handler;
- (void)_mountToDetectDMGImageBundle:(id)bundle copyMoveStrategy:(unsigned long long)strategy dawToken:(id)token certificateURL:(id)url certificateAuth:(id)auth completionQueue:(id)queue completionHandler:(id /* block */)handler;
- (_Bool)notifyServiceCryptexWillUnmountForMountURL:(id)url withError:(id *)error;
- (void)deleteDiskImage:(id)image completionQueue:(id)queue completionHandler:(id /* block */)handler;
- (void)verifyDiskImage:(id)image completionQueue:(id)queue completionHandler:(id /* block */)handler;
- (void)prepareDYLDSharedCacheWithRuntimeBundle:(id)bundle forceRecreation:(_Bool)recreation completionQueue:(id)queue completionHandler:(id /* block */)handler;
- (void)removeDYLDSharedCacheWithRuntimeBundle:(id)bundle completionQueue:(id)queue completionHandler:(id /* block */)handler;
- (void)_didUseRuntimeBundleAtURL:(id)url;

@end

#endif /* SimDiskImageManager_h */
