//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.645, BuildCommit: 6e9f98c9dbaacd42e09240f9386168f3b8317f96)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14, SDK: 16, Tool: ld (1215)
//    - LC_SOURCE_VERSION: 1031.0.0.0.0
//
#ifndef SimDeviceDataMigrationPluginResult_h
#define SimDeviceDataMigrationPluginResult_h
@import Foundation;

@class NSObject, NSString;

@interface SimDeviceDataMigrationPluginResult : NSObject

@property (copy, nonatomic) NSString *identifier;
@property (copy, nonatomic) NSString *bundlePath;
@property (nonatomic) double duration;
@property (copy, nonatomic) NSString *phaseDescription;
@property (nonatomic) _Bool isSuccess;
@property (nonatomic) unsigned int status;
@property (readonly, nonatomic) NSString *component;

/* instance methods */
- (id)initWithIdentifier:(id)identifier info:(id)info;
- (id)description;

@end

#endif /* SimDeviceDataMigrationPluginResult_h */
