//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.645, BuildCommit: 6e9f98c9dbaacd42e09240f9386168f3b8317f96)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14, SDK: 16, Tool: ld (1215)
//    - LC_SOURCE_VERSION: 1031.0.0.0.0
//
#ifndef SimDeviceBootInfo_h
#define SimDeviceBootInfo_h
@import Foundation;

#include "NSObjectROCKDeserializable-Protocol.h"
#include "NSObjectROCKSerializable-Protocol.h"

@class NSDictionary, NSObject, NSString;

@interface SimDeviceBootInfo : NSObject <NSObjectROCKDeserializable, NSObjectROCKSerializable>

@property (readonly) NSUInteger hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) unsigned int status;
@property (nonatomic) double bootElapsedTime;
@property (nonatomic) _Bool isTerminalStatus;
@property (retain, nonatomic) NSDictionary *info;
@property (readonly, nonatomic) NSString *migrationPhaseDescription;
@property (readonly, nonatomic) double migrationElapsedTime;
@property (readonly, nonatomic) NSDictionary *migrationPluginDetails;

/* class methods */
+ (id)rockDecodeWithXPCObject:(id)xpcobject sessionManager:(id)manager error:(id *)error;
+ (_Bool)supportsSecureCoding;

/* instance methods */
- (id)rockEncodeWithSessionManager:(id)manager error:(id *)error;
- (id)initWithElapsedTime:(double)time status:(unsigned int)status info:(id)info;
- (_Bool)isEqual:(id)equal;

@end

#endif /* SimDeviceBootInfo_h */
