//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.645, BuildCommit: 6e9f98c9dbaacd42e09240f9386168f3b8317f96)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14, SDK: 16, Tool: ld (1215)
//    - LC_SOURCE_VERSION: 1031.0.0.0.0
//
#ifndef SimDisplayDescriptorState_Protocol_h
#define SimDisplayDescriptorState_Protocol_h
@import Foundation;

#include "ROCKMemoizable-Protocol.h"
#include "SimDeviceIOPortDescriptorState-Protocol.h"

@class NSURL;

@protocol SimDisplayDescriptorState <ROCKMemoizable, SimDeviceIOPortDescriptorState>

@required

@property (readonly, nonatomic) unsigned short displayClass;
@property (readonly, nonatomic) unsigned int defaultWidthForDisplay;
@property (readonly, nonatomic) unsigned int defaultHeightForDisplay;
@property (readonly, nonatomic) unsigned int defaultPixelFormat;
@property (readonly, nonatomic) NSURL *mask;

@optional

@end

#endif /* SimDisplayDescriptorState_Protocol_h */
