//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.645, BuildCommit: 6e9f98c9dbaacd42e09240f9386168f3b8317f96)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14, SDK: 16, Tool: ld (1215)
//    - LC_SOURCE_VERSION: 1031.0.0.0.0
//
#ifndef SimDeviceSet_h
#define SimDeviceSet_h
@import Foundation;

#include "SimDeviceNotificationManager.h"
#include "SimDeviceNotifier-Protocol.h"
#include "SimServiceContext.h"

@class NSArray, NSDictionary, NSMutableDictionary, NSObject, NSString, SimDevice, SimDeviceType, SimRuntime;
@protocol OS_dispatch_queue, OS_dispatch_source;

@interface SimDeviceSet : NSObject <SimDeviceNotifier>

@property (copy, nonatomic) NSString * _Nullable setPath;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> * _Nullable deviceNotificationQueue;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> * _Nullable devicesQueue;
@property (retain, nonatomic) NSMutableDictionary * _Nullable _devicesByUDID;
@property (retain, nonatomic) NSMutableDictionary * _Nullable devicesNotificationRegIDs;
@property (retain, nonatomic) NSMutableDictionary * _Nullable _devicePairsByUUID;
@property (retain, nonatomic) NSMutableDictionary * _Nullable devicePairsNotificationRegIDs;
@property (retain, nonatomic) NSMutableDictionary * _Nullable deviceDeletionCountByUDID;
@property (retain, nonatomic) SimServiceContext * _Nullable serviceContext;
@property (retain, nonatomic) SimDeviceNotificationManager * _Nullable notificationManager;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> * _Nullable defaultCreatedDevicesQueue;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> * _Nullable deviceDeletionQueue;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> * _Nullable hostDeathQueue;
@property (retain, nonatomic) NSMutableDictionary * _Nullable hostDeathSourceByUDID;
@property (retain, nonatomic) NSMutableDictionary * _Nullable defaultCreatedDevices;
@property (retain, nonatomic) NSString * _Nullable defaultCreatedLastDeveloperDir;
@property (retain, nonatomic) NSObject<OS_dispatch_source> * _Nullable saveToDiskSource;
@property (readonly, nonatomic) NSDictionary<NSUUID *, SimDevice *> * _Nullable devicesByUDID;
@property (readonly, nonatomic) NSArray<SimDevice *> * _Nullable devices;
@property (readonly, nonatomic) NSArray<SimDevice *> * _Nullable availableDevices;
@property (readonly, nonatomic) NSDictionary * _Nullable devicePairsByUUID;
@property (readonly, nonatomic) NSArray * _Nullable devicePairs;
@property (readonly, nonatomic) NSArray * _Nullable availableDevicePairs;

/* class methods */
+ (_Nullable id)defaultSetPath;
+ (_Nullable id)saveToDiskQueue;
+ (_Nullable id)validGizmoVersionByCompanionVersion;

/* instance methods */
- (_Bool)isDefaultSet;
- (_Bool)subscribeToNotificationsWithError:(id _Nullable * _Nullable)error;
- (_Nullable id)initWithSetPath:(_Nullable id)path serviceContext:(_Nullable id)context;
- (_Bool)processDeviceSetPlist;
- (void)saveToDisk;
- (void)_onSaveToDiskQueue_saveToDisk;
- (_Nullable id)description;
- (_Bool)isDeviceInSet:(_Nullable id)set;
- (_Nullable id)devicePairsContainingDeviceUDID:(_Nullable id)udid;
- (_Nullable id)devicePairsContainingDevice:(_Nullable id)device;
- (void)updateDefaultDevicesAndPairingsForDeveloperDir:(_Nullable id)dir force:(_Bool)force;
- (void)updateDefaultDevicesAndPairingsAsyncForDeveloperDir:(_Nullable id)dir force:(_Bool)force;
- (void)_onDefaultCreatedDevicesQueue_updateDefaultDevicesAndPairingsForDeveloperDir:(_Nullable id)dir force:(_Bool)force;
- (void)_onDefaultCreatedDevicesQueue_updateDefaultDevicesForDeveloperDir:(_Nullable id)dir;
- (void)_onDefaultCreatedDevicesQueue_updateDefaultDevicePairingsForDeveloperDir:(_Nullable id)dir;
- (void)_onDefaultCreatedDevicesQueue_updateDefaultDevicePairingsWithCompanionRuntime:(_Nullable id)runtime gizmoRuntime:(_Nullable id)runtime;
- (void)addDeviceAsync:(_Nullable id)async;
- (void)addDevice:(_Nullable id)device;
- (void)_onDeviceQueue_addDevice:(_Nullable id)device;
- (void)removeDeviceAsync:(_Nullable id)async;
- (void)addDevicePairAsync:(_Nullable id)async;
- (void)addDevicePair:(_Nullable id)pair;
- (void)_onDevicesQueue_addDevicePair:(_Nullable id)pair;
- (void)removeDevicePairAsync:(_Nullable id)async;
- (unsigned long long)registerNotificationHandlerOnQueue:(_Nullable id)queue handler:(_Nullable id /* block */)handler;
- (void)sendNotification:(_Nullable id)notification;
- (_Bool)unregisterNotificationHandler:(unsigned long long)handler error:(id _Nullable * _Nullable)error;
- (_Nullable id)_awaitDeviceWithUDID:(_Nullable id)udid;
- (_Nullable id)_awaitDevicePairWithUUID:(_Nullable id)uuid;
- (void)createDeviceAsyncWithType:(_Nullable id)type runtime:(_Nullable id)runtime name:(_Nullable id)name completionHandler:(_Nullable id /* block */)handler;
- (void)createDeviceAsyncWithType:(_Nullable id)type runtime:(_Nullable id)runtime name:(_Nullable id)name completionQueue:(_Nullable id)queue completionHandler:(_Nullable id /* block */)handler;
- (void)createDeviceAsyncWithType:(_Nullable id)type runtime:(_Nullable id)runtime name:(_Nullable id)name options:(_Nullable id)options completionQueue:(_Nullable id)queue completionHandler:(_Nullable id /* block */)handler;
- (nullable SimDevice *)createDeviceWithType:(nonnull SimDeviceType *)type runtime:(nonnull SimRuntime *)runtime name:(nonnull NSString *)name error:(NSError * _Nullable * _Nullable)error;
- (nullable SimDevice *)createDeviceWithType:(nonnull SimDeviceType *)type runtime:(nonnull SimRuntime *)runtime name:(nonnull NSString *)name options:(_Nullable id)options error:(NSError * _Nullable * _Nullable)error;
- (void)deleteDeviceAsync:(_Nullable id)async completionQueue:(_Nullable id)queue completionHandler:(_Nullable id /* block */)handler;
- (void)deleteDeviceAsync:(_Nullable id)async completionHandler:(_Nullable id /* block */)handler;
- (BOOL)deleteDevice:(nonnull SimDevice *)device error:(NSError * _Nullable * _Nullable)error __attribute__((swift_error(nonnull_error)));
- (void)cloneDeviceAsync:(_Nullable id)async name:(_Nullable id)name completionQueue:(_Nullable id)queue completionHandler:(_Nullable id /* block */)handler;
- (void)cloneDeviceAsync:(_Nullable id)async name:(_Nullable id)name toSet:(_Nullable id)set completionQueue:(_Nullable id)queue completionHandler:(_Nullable id /* block */)handler;
- (void)cloneDeviceAsync:(_Nullable id)async name:(_Nullable id)name options:(_Nullable id)options toSet:(_Nullable id)set completionQueue:(_Nullable id)queue completionHandler:(_Nullable id /* block */)handler;
- (_Nullable id)cloneDevice:(_Nullable id)device name:(_Nullable id)name error:(id _Nullable * _Nullable)error;
- (_Nullable id)cloneDevice:(_Nullable id)device name:(_Nullable id)name options:(_Nullable id)options error:(id _Nullable * _Nullable)error;
- (_Nullable id)cloneDevice:(_Nullable id)device name:(_Nullable id)name toSet:(_Nullable id)set error:(id _Nullable * _Nullable)error;
- (_Nullable id)cloneDevice:(_Nullable id)device name:(_Nullable id)name options:(_Nullable id)options toSet:(_Nullable id)set error:(id _Nullable * _Nullable)error;
- (void)shutdownBootedDevicesMatchingVolumeURL:(_Nullable id)url completionGroup:(_Nullable id)group deviceShutdownHandler:(_Nullable id /* block */)handler;
- (_Bool)testDevicePairingBetweenGizmo:(_Nullable id)gizmo companion:(_Nullable id)companion error:(id _Nullable * _Nullable)error;
- (void)createDevicePairAsyncWithGizmo:(_Nullable id)gizmo companion:(_Nullable id)companion completionQueue:(_Nullable id)queue completionHandler:(_Nullable id /* block */)handler;
- (void)createDevicePairAsyncWithGizmo:(_Nullable id)gizmo companion:(_Nullable id)companion completionHandler:(_Nullable id /* block */)handler;
- (_Nullable id)createDevicePairWithGizmo:(_Nullable id)gizmo companion:(_Nullable id)companion error:(id _Nullable * _Nullable)error;
- (void)unpairDevicePairAsync:(_Nullable id)async completionQueue:(_Nullable id)queue completionHandler:(_Nullable id /* block */)handler;
- (void)unpairDevicePairAsync:(_Nullable id)async completionHandler:(_Nullable id /* block */)handler;
- (_Bool)unpairDevicePair:(_Nullable id)pair error:(id _Nullable * _Nullable)error;
- (void)runBackgroundDeviceDeleteAsync;
- (_Bool)setupHostDeathWatchForDevice:(_Nullable id)device deathPort:(_Nullable id)port error:(id _Nullable * _Nullable)error;
- (void)handleXPCNotification:(_Nullable id)xpcnotification;
- (void)handleXPCNotificationDeviceAdded:(_Nullable id)added;
- (void)handleXPCNotificationDeviceRemoved:(_Nullable id)removed;
- (void)handleXPCNotificationDevicePairAdded:(_Nullable id)added;
- (void)handleXPCNotificationDevicePairRemoved:(_Nullable id)removed;
- (void)handleXPCRequest:(_Nullable id)xpcrequest;
- (void)handleXPCRequestCreateDevice:(_Nullable id)device;
- (void)handleXPCRequestCloneDevice:(_Nullable id)device device:(_Nullable id)device;
- (void)handleXPCRequestDeleteDevice:(_Nullable id)device device:(_Nullable id)device;
- (void)handleXPCRequestPair:(_Nullable id)pair;
- (void)handleXPCRequestUnpair:(_Nullable id)unpair;

@end

#endif /* SimDeviceSet_h */
