//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.645, BuildCommit: 6e9f98c9dbaacd42e09240f9386168f3b8317f96)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14, SDK: 16, Tool: ld (1215)
//    - LC_SOURCE_VERSION: 1031.0.0.0.0
//
#ifndef SimDiskImageRuntimeInfo_h
#define SimDiskImageRuntimeInfo_h
@import Foundation;

@class NSObject, NSString, NSURL;

@interface SimDiskImageRuntimeInfo : NSObject

@property (copy, nonatomic) NSString *runtimeIdentifier;
@property (retain, nonatomic) NSURL *runtimeBundleURL;
@property (copy, nonatomic) NSString *platformIdentifier;
@property (copy, nonatomic) NSString *versionString;
@property (copy, nonatomic) NSString *buildVersionString;
@property (nonatomic) _Bool isInternal;
@property (readonly, nonatomic) NSString *platformName;

/* class methods */
+ (id)platformNameForIdentifier:(id)identifier;

/* instance methods */
- (id)initWithIdentifier:(id)identifier runtimeBundleURL:(id)url platformIdentifier:(id)identifier versionString:(id)string buildVersionString:(id)string isInternal:(_Bool)internal;
- (id)initFromXPCDictionary:(id)xpcdictionary error:(id *)error;
- (id)description;

@end

#endif /* SimDiskImageRuntimeInfo_h */
