//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.645, BuildCommit: 6e9f98c9dbaacd42e09240f9386168f3b8317f96)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14, SDK: 16, Tool: ld (1215)
//    - LC_SOURCE_VERSION: 1031.0.0.0.0
//
#ifndef SimIdentityClient_h
#define SimIdentityClient_h
@import Foundation;

#include "OS_xpc_object-Protocol.h"
#include "SimIdentityDevice.h"
#include "SimIdentitySystem-Protocol.h"

@class NSObject;
@protocol OS_dispatch_queue;

@interface SimIdentityClient : NSObject

@property (retain, nonatomic) NSObject<OS_dispatch_queue> *queue;
@property (retain, nonatomic) NSObject<OS_xpc_object> *connection;
@property (weak, nonatomic) id <SimIdentitySystem> identitySystem;
@property (weak, nonatomic) SimIdentityDevice *identityDevice;

/* instance methods */
- (id)initWithNewPeer:(id)peer identityDevice:(id)device identitySystem:(id)system;
- (void)_onQueue_handleMessage:(id)message;

@end

#endif /* SimIdentityClient_h */
