//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.645, BuildCommit: 6e9f98c9dbaacd42e09240f9386168f3b8317f96)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14, SDK: 16, Tool: ld (1215)
//    - LC_SOURCE_VERSION: 1031.0.0.0.0
//
#ifndef SimLaunchHostConnection_h
#define SimLaunchHostConnection_h
@import Foundation;

#include "OS_xpc_object-Protocol.h"

@class NSMapTable, NSObject, NSString;
@protocol OS_dispatch_queue;

@interface SimLaunchHostConnection : NSObject

@property (copy, nonatomic) NSString *serviceName;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> *queue;
@property (retain, nonatomic) NSObject<OS_xpc_object> *xpcConnection;
@property (retain, nonatomic) NSMapTable *libLaunchInstances;
@property (nonatomic) _Bool pendingResync;

/* class methods */
+ (_Bool)parseErrorReply:(id)reply error:(id *)error;
+ (id)allJobLabels;
+ (id)connectionForArch:(id)arch error:(id *)error;

/* instance methods */
- (id)initWithServiceName:(id)name;
- (void)_connectToServiceName:(id)name;
- (void)dealloc;
- (void)_checkAndResyncIfNeeded;
- (id)loadLibLaunchAtURL:(id)url equivalentIOSVersion:(unsigned int)iosversion error:(id *)error;
- (void)unloadLibLaunch:(id)launch;
- (void)sendMessage:(id)message;
- (id)sendMessageSyncWithReply:(id)reply;
- (void)sendMessage:(id)message replyQueue:(id)queue replyHandler:(id /* block */)handler;
- (void)_instanceWillDealloc:(id)dealloc;
- (void)_onQueue_launchInstanceUnload:(id)unload;
- (id)_loadRequestForInstance:(id)instance existingUUID:(id)uuid;
- (id)_sendLoadRequestForInstance:(id)instance existingUUID:(id)uuid error:(id *)error;
- (void)_onQueue_sendAsyncLoadRequestForInstance:(id)instance existingUUID:(id)uuid completionQueue:(id)queue completionHandler:(id /* block */)handler;

@end

#endif /* SimLaunchHostConnection_h */
