//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.645, BuildCommit: 6e9f98c9dbaacd42e09240f9386168f3b8317f96)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14, SDK: 16, Tool: ld (1215)
//    - LC_SOURCE_VERSION: 1031.0.0.0.0
//
#ifndef SimLibLaunchInstance_h
#define SimLibLaunchInstance_h
@import Foundation;

#include "SimLaunchHostConnection.h"

@class NSObject, NSURL, NSUUID;

@interface SimLibLaunchInstance : NSObject

@property (retain, nonatomic) NSUUID *libLaunchUUID;
@property (retain, nonatomic) NSURL *libLaunchURL;
@property (nonatomic) unsigned int equivalentIOSVersion;
@property (weak, nonatomic) SimLaunchHostConnection *connection;

/* instance methods */
- (id)initWithLibLaunchURL:(id)url equivalentIOSVersion:(unsigned int)iosversion connection:(id)connection;
- (void)dealloc;

@end

#endif /* SimLibLaunchInstance_h */
