//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.645, BuildCommit: 6e9f98c9dbaacd42e09240f9386168f3b8317f96)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14, SDK: 16, Tool: ld (1215)
//    - LC_SOURCE_VERSION: 1031.0.0.0.0
//
#ifndef SimLaunchHostClient_h
#define SimLaunchHostClient_h
@import Foundation;

#include "SimLaunchHostConnection.h"
#include "SimLibLaunchInstance.h"

@class NSObject;

@interface SimLaunchHostClient : NSObject {
    /* instance variables */
    struct os_unfair_lock_s { unsigned int _os_unfair_lock_opaque; } _lock;
}

@property (retain, nonatomic) SimLaunchHostConnection *connection;
@property (retain, nonatomic) SimLibLaunchInstance *libLaunchInstance;

/* class methods */
+ (id)launchHostClientForRuntime:(id)runtime error:(id *)error;

/* instance methods */
- (id)initWithConnection:(id)connection libLaunchInstance:(id)instance error:(id *)error;
- (_Bool)_parseErrorReply:(id)reply error:(id *)error;
- (_Bool)startNewSession:(id)session endpointsToRegister:(id)_register bindPort:(unsigned int)port deathQueue:(id)queue deathHandler:(id /* block */)handler error:(id *)error;
- (_Bool)registerServiceInSession:(id)session serviceName:(id)name servicePort:(unsigned int)port error:(id *)error;
- (_Bool)unregisterServiceFromSession:(id)session serviceName:(id)name error:(id *)error;
- (_Bool)findServiceInSession:(id)session serviceName:(id)name servicePort:(unsigned int *)port error:(id *)error;
- (id)getEnvValueInSession:(id)session named:(id)named;
- (_Bool)spawnInSession:(id)session program:(id)program arguments:(id)arguments environment:(id)environment cwd:(id)cwd standardInput:(id)input standardOutput:(id)output standardError:(id)error binpref:(int)binpref flags:(unsigned long long)flags pid:(int *)pid terminationQueue:(id)queue terminationHandler:(id /* block */)handler error:(id *)error;

@end

#endif /* SimLaunchHostClient_h */
