//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.645, BuildCommit: 6e9f98c9dbaacd42e09240f9386168f3b8317f96)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14, SDK: 16, Tool: ld (1215)
//    - LC_SOURCE_VERSION: 1031.0.0.0.0
//
#ifndef SimNearbyPeer_h
#define SimNearbyPeer_h
@import Foundation;

#include "OS_xpc_object-Protocol.h"

@class NSObject, NSString;

@interface SimNearbyPeer : NSObject

@property (retain, nonatomic) NSObject<OS_xpc_object> *connection;
@property (copy, nonatomic) NSString *discoveryToken;

/* instance methods */
- (id)initWithConnection:(id)connection discoveryToken:(id)token;
- (void)dealloc;

@end

#endif /* SimNearbyPeer_h */
