//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.645, BuildCommit: 6e9f98c9dbaacd42e09240f9386168f3b8317f96)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14, SDK: 16, Tool: ld (1215)
//    - LC_SOURCE_VERSION: 1031.0.0.0.0
//
#ifndef SimNotificationManager_h
#define SimNotificationManager_h
@import Foundation;

@class NSMutableDictionary, NSObject, NSString;
@protocol OS_dispatch_queue;

@interface SimNotificationManager : NSObject

@property (copy, nonatomic) NSString *name;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> *handlersQueue;
@property (retain, nonatomic) NSMutableDictionary *handlers;
@property (nonatomic) unsigned long long next_regID;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> *sendQueue;

/* class methods */
+ (Class)registrationTokenClass;

/* instance methods */
- (id)initWithName:(id)name;
- (id)registerNotificationHandler:(id /* block */)handler;
- (id)registerNotificationHandlerOnQueue:(id)queue handler:(id /* block */)handler;
- (_Bool)unregisterNotificationHandler:(unsigned long long)handler;
- (void)sendNotification:(id)notification;
- (void)sendNotification:(id)notification waitForExecution:(_Bool)execution completionQueue:(id)queue completionBlock:(id /* block */)block;

@end

#endif /* SimNotificationManager_h */
