//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.645, BuildCommit: 6e9f98c9dbaacd42e09240f9386168f3b8317f96)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14, SDK: 16, Tool: ld (1215)
//    - LC_SOURCE_VERSION: 1031.0.0.0.0
//
#ifndef SimPlatformInfo_h
#define SimPlatformInfo_h
@import Foundation;

@class NSArray, NSObject, NSString, NSURL;

@interface SimPlatformInfo : NSObject

@property (retain, nonatomic) NSURL *platformDirectory;
@property (copy, nonatomic) NSString *platformIdentifier;
@property (retain, nonatomic) NSArray *platformSDKs;

/* instance methods */

@end

#endif /* SimPlatformInfo_h */
