//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.645, BuildCommit: 6e9f98c9dbaacd42e09240f9386168f3b8317f96)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14, SDK: 16, Tool: ld (1215)
//    - LC_SOURCE_VERSION: 1031.0.0.0.0
//
#ifndef SimRuntime_h
#define SimRuntime_h
@import Foundation;

#include "SimDeviceIORuntimeInterface-Protocol.h"
#include "SimLaunchHostClient.h"
#include "SimProfileBundle.h"
#include "SimRuntimePairingRequirements.h"

@class NSArray, NSDictionary, NSObject, NSString, NSURL;
@protocol OS_dispatch_queue;

@interface SimRuntime : NSObject <SimDeviceIORuntimeInterface>

@property (retain, nonatomic) SimProfileBundle * _Nullable bundle;
@property (nonatomic) NSString * _Nullable name;
@property (copy, nonatomic) NSString * _Nullable shortName;
@property (nonatomic) NSString * _Nullable identifier;
@property (nonatomic) unsigned int version;
@property (nonatomic) unsigned int equivalentIOSVersion;
@property (copy, nonatomic) NSString * _Nullable versionString;
@property (copy, nonatomic) NSString * _Nullable buildVersionString;
@property (copy, nonatomic) NSString * _Nullable root;
@property (copy, nonatomic) NSDictionary * _Nullable supportedFeatures;
@property (copy, nonatomic) NSDictionary * _Nullable supportedFeaturesConditionalOnDeviceType;
@property (nonatomic) NSDictionary * _Nullable requiredHostServices;
@property (copy, nonatomic) NSDictionary * _Nullable forwardHostNotifications;
@property (copy, nonatomic) NSDictionary * _Nullable forwardHostNotificationsWithState;
@property (nonatomic) NSString * _Nullable platformIdentifier;
@property (copy, nonatomic) NSString * _Nullable resourcesPlatformIdentifier;
@property (copy, nonatomic) NSString * _Nullable devicePlatformFolderName;
@property (copy, nonatomic) NSString * _Nullable simulatorPlatformFolderName;
@property (copy, nonatomic) NSArray * _Nullable supportedProductFamilyIDs;
@property (retain, nonatomic) SimRuntimePairingRequirements * _Nullable pairingRequirements;
@property (copy, nonatomic) NSDictionary * _Nullable environment_extra;
@property (retain, nonatomic) SimLaunchHostClient * _Nullable launchHostClient;
@property (copy, nonatomic) NSArray * _Nullable aliases;
@property (nonatomic) unsigned int minHostVersion;
@property (nonatomic) unsigned int maxHostVersion;
@property (nonatomic) unsigned int minCoreSimulatorFrameworkVersion;
@property (nonatomic) unsigned int maxCoreSimulatorFrameworkVersion;
@property (copy, nonatomic) NSArray * _Nullable supportedArchs;
@property (copy, nonatomic) NSArray * _Nullable supportedArchStrings;
@property (copy, nonatomic) NSString * _Nullable dyldSharedCachePath;
@property (nonatomic) _Bool supportsDyldSharedCache;
@property (nonatomic) _Bool isInternal;
@property (readonly, nonatomic) _Bool available;
@property (readonly, nonatomic) NSURL * _Nullable runtimeRootURL;
@property (readonly, nonatomic) NSURL * _Nullable bundleURL;
@property (readonly, nonatomic) NSURL * _Nullable platformResourcesURL;
@property (readonly, nonatomic) NSObject<OS_dispatch_queue> * _Nullable memoizableSerializerQueue;
@property (readonly) NSUInteger hash;
@property (readonly) _Nullable Class superclass;
@property (readonly, copy) NSString * _Nullable description;
@property (readonly, copy) NSString * _Nullable debugDescription;

/* class methods */
+ (_Nullable id)unsupportedDeviceTypesForRuntimeMatchingBuildVersionPrefix;
+ (_Nullable id)updatedMaxHostVersions;
+ (_Nullable id)updatedMaxCoreSimulatorVersions;
+ (unsigned int)equivalentIOSVersionForVersion:(unsigned int)version profile:(_Nullable id)profile platformIdentifier:(_Nullable id)identifier;
+ (_Bool)removeAllDyldSharedCachesWithError:(id _Nullable * _Nullable)error;

/* instance methods */
- (_Nullable id)initWithBundle:(_Nullable id)bundle error:(id _Nullable * _Nullable)error;
- (_Nullable id)environment;
- (_Nullable id)platformResourcesPath;
- (_Nullable id)bundlePath;
- (_Bool)supportsDeviceType:(_Nullable id)type;
- (_Bool)supportsFeature:(_Nullable id)feature;
- (_Bool)supportsFeatureConditionally:(_Nullable id)conditionally;
- (_Bool)isEqualToRuntime:(_Nullable id)runtime;
- (_Bool)isEqual:(_Nullable id)equal;
- (long long)compare:(_Nullable id)compare;
- (_Nullable id)sampleContentPath;
- (_Bool)createInitialContentPath:(_Nullable id)path error:(id _Nullable * _Nullable)error;
- (_Nullable id)libLaunchURL;
- (_Bool)isAvailableWithError:(id _Nullable * _Nullable)error;
- (_Bool)rebuildDyldSharedCacheWithPolicy:(unsigned long long)policy error:(id _Nullable * _Nullable)error;
- (void)rebuildDyldSharedCacheWithPolicy:(unsigned long long)policy completionQueue:(_Nullable id)queue completionHandler:(_Nullable id /* block */)handler;
- (_Bool)dyldSharedCacheIsUsable;
- (_Bool)resetDyldSharedCacheWithError:(id _Nullable * _Nullable)error;
- (_Nullable id)deviceEquivalentPlatformIdentifier;
- (_Nullable id)usageTrackerForArch:(_Nullable id)arch error:(id _Nullable * _Nullable)error;
- (_Nullable id)initForTest:(_Nullable id)test;

@end

#endif /* SimRuntime_h */
