//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.645, BuildCommit: 6e9f98c9dbaacd42e09240f9386168f3b8317f96)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14, SDK: 16, Tool: ld (1215)
//    - LC_SOURCE_VERSION: 1031.0.0.0.0
//
#ifndef SimSelectedRuntimePolicyResult_h
#define SimSelectedRuntimePolicyResult_h
@import Foundation;

#include "SimRuntime.h"

@class NSObject, NSString, NSURL;

@interface SimSelectedRuntimePolicyResult : NSObject

@property (retain, nonatomic) NSURL *platformDirectory;
@property (retain, nonatomic) NSURL *SDKDirectory;
@property (copy, nonatomic) NSString *platformIdentifier;
@property (copy, nonatomic) NSString *SDKCanonicalName;
@property (nonatomic) unsigned int SDKVersion;
@property (copy, nonatomic) NSString *SDKVersionString;
@property (copy, nonatomic) NSString *SDKBuild;
@property (copy, nonatomic) NSString *chosenRuntimeBuild;
@property (weak, nonatomic) SimRuntime *chosenRuntime;
@property (copy, nonatomic) NSString *userOverridenRuntimeBuild;
@property (weak, nonatomic) SimRuntime *userOverriddenRuntime;
@property (copy, nonatomic) NSString *preferredRuntimeBuild;
@property (weak, nonatomic) SimRuntime *preferredRuntime;
@property (copy, nonatomic) NSString *defaultRuntimeBuild;
@property (weak, nonatomic) SimRuntime *defaultRuntime;

/* instance methods */
- (id)initWithPlatformDirectory:(id)directory sdkDirectory:(id)directory platformIdentifier:(id)identifier sdkCanonicalName:(id)name sdkVersion:(unsigned int)version sdkVersionString:(id)string sdkBuild:(id)build chosenRuntimeBuild:(id)build chosenRuntime:(id)runtime userOverriddenRuntimeBuild:(id)build userOverriddenRuntime:(id)runtime preferredRuntimeBuild:(id)build preferredRuntime:(id)runtime defaultRuntimeBuild:(id)build defaultRuntime:(id)runtime;

@end

#endif /* SimSelectedRuntimePolicyResult_h */
