//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.645, BuildCommit: 6e9f98c9dbaacd42e09240f9386168f3b8317f96)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14, SDK: 16, Tool: ld (1215)
//    - LC_SOURCE_VERSION: 1031.0.0.0.0
//
#ifndef SimUsageTracker_h
#define SimUsageTracker_h
@import Foundation;

@class NSDate, NSObject, NSString;

@interface SimUsageTracker : NSObject

@property (copy, nonatomic) NSString *identifier;
@property (copy, nonatomic) NSString *key;
@property (readonly, nonatomic) NSDate *lastUsage;

/* class methods */
+ (id)sharedTrackerWithIdentifier:(id)identifier;

/* instance methods */
- (id)initWithIdentifier:(id)identifier;
- (void)use;

@end

#endif /* SimUsageTracker_h */
