//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.645, BuildCommit: 6e9f98c9dbaacd42e09240f9386168f3b8317f96)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14, SDK: 16, Tool: ld (1215)
//    - LC_SOURCE_VERSION: 1031.0.0.0.0
//
#ifndef SimVolumeManager_h
#define SimVolumeManager_h
@import Foundation;

#include "SimNotificationManager.h"
#include "SimServiceContext.h"

@class NSMutableDictionary, NSObject;
@protocol OS_dispatch_queue;

@interface SimVolumeManager : SimNotificationManager {
    /* instance variables */
    NSMutableDictionary *_bsdNameToUnmountRecord;
}

@property (nonatomic) struct __DASession * session;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> *sessionQueue;
@property (retain, nonatomic) SimServiceContext *serviceContext;

/* class methods */
+ (id)sharedInstance;

/* instance methods */
- (id)initCommonWithName:(id)name;
- (void)dealloc;
- (void)startSession;
- (_Bool)_shouldIgnoreDiskMountedAt:(id)at;
- (void)_diskAppeared:(struct __DADisk *)appeared diskDescription:(id)description reportConsequences:(_Bool)consequences addedDeveloperDir:(id)dir completionQueue:(id)queue completionHandler:(id /* block */)handler;
- (void)_disk:(struct __DADisk *)_disk propertiesChanged:(id)changed diskDescription:(id)description reportConsequences:(_Bool)consequences completionQueue:(id)queue completionHandler:(id /* block */)handler;
- (void)_diskDisappeared:(struct __DADisk *)disappeared diskDescription:(id)description reportConsequences:(_Bool)consequences completionQueue:(id)queue completionHandler:(id /* block */)handler;
- (void)_diskIdle;
- (struct __DADissenter *)_diskUnmountApproval:(struct __DADisk *)approval diskDescription:(id)description;
- (_Bool)_sendUnmountNotificationWithDisk:(struct __DADisk *)disk timeout:(double)timeout reportConsequences:(_Bool)consequences completionQueue:(id)queue completionHandler:(id /* block */)handler;
- (void)notifyCryptexWillUnmountForMountURL:(id)url;

@end

#endif /* SimVolumeManager_h */
