//
//   Generated by https://github.com/blacktop/ipsw (Version: 3.1.645, BuildCommit: 6e9f98c9dbaacd42e09240f9386168f3b8317f96)
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14, SDK: 16, Tool: ld (1215)
//    - LC_SOURCE_VERSION: 1031.0.0.0.0
//
#ifndef SimVolumeManagerNotification_h
#define SimVolumeManagerNotification_h
@import Foundation;

@class NSMutableArray, NSObject, NSString, NSURL;
@protocol OS_dispatch_group;

@interface SimVolumeManagerNotification : NSObject

@property (nonatomic) unsigned long long notificationType;
@property (nonatomic) struct __CFDictionary * diskInfo;
@property (retain, nonatomic) NSString *bsdDeviceName;
@property (retain, nonatomic) NSString *mountPath;
@property (retain, nonatomic) NSURL *mountURL;
@property (retain, nonatomic) NSObject<OS_dispatch_group> *synchronizingGroup;
@property (retain, nonatomic) NSMutableArray *consequences;
@property (nonatomic) _Bool reportConsequences;
@property (readonly, nonatomic) NSString *volumeName;

/* class methods */
+ (id)notificationWithType:(unsigned long long)type disk:(struct __DADisk *)disk synchronizingGroup:(id)group reportConsequences:(_Bool)consequences;
+ (id)notificationWithTypeCryptexVolumeWillUnmountForMountURL:(id)url;

/* instance methods */
- (void)dealloc;
- (void)noteConsequence:(unsigned long long)consequence onTarget:(unsigned long long)target withIdentifier:(id)identifier atPath:(id)path;
- (id)description;

@end

#endif /* SimVolumeManagerNotification_h */
